package handler

import (
	"github.com/dafibh/fortuna/fortuna-backend/internal/middleware"
	"github.com/labstack/echo/v4"
)

// RegisterRoutes sets up all API routes
func RegisterRoutes(e *echo.Echo, dualAuth *middleware.DualAuthMiddleware, rateLimiter *middleware.RateLimiter, authHandler *AuthHandler, profileHandler *ProfileHandler, accountHandler *AccountHandler, transactionHandler *TransactionHandler, monthHandler *MonthHandler, dashboardHandler *DashboardHandler, budgetCategoryHandler *BudgetCategoryHandler, budgetHandler *BudgetHandler, ccHandler *CCHandler, recurringTemplateHandler *RecurringTemplateHandler, loanProviderHandler *LoanProviderHandler, loanHandler *LoanHandler, loanPaymentHandler *LoanPaymentHandler, wishlistHandler *WishlistHandler, wishlistItemHandler *WishlistItemHandler, wishlistPriceHandler *WishlistPriceHandler, wishlistNoteHandler *WishlistNoteHandler, imageHandler *ImageHandler, wsHandler *WebSocketHandler, apiTokenHandler *APITokenHandler, settlementHandler *SettlementHandler) {
	// WebSocket route (auth via query param token)
	e.GET("/ws", wsHandler.HandleWS)

	// API version 1
	api := e.Group("/api/v1")

	// Auth routes (JWT only - session management)
	auth := api.Group("/auth")
	auth.Use(dualAuth.JWTOnly())
	auth.POST("/callback", authHandler.Callback)
	auth.GET("/me", authHandler.Me)
	auth.POST("/logout", authHandler.Logout)

	// Profile routes (JWT only - user settings)
	profile := api.Group("/profile")
	profile.Use(dualAuth.JWTOnly())
	profile.GET("", profileHandler.GetProfile)
	profile.PUT("", profileHandler.UpdateProfile)

	// Account routes (dual auth with rate limiting)
	accounts := api.Group("/accounts")
	accounts.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	accounts.POST("", accountHandler.CreateAccount)
	accounts.GET("", accountHandler.GetAccounts)
	accounts.GET("/cc-summary", accountHandler.GetCCSummary)
	accounts.PUT("/:id", accountHandler.UpdateAccount)
	accounts.DELETE("/:id", accountHandler.DeleteAccount)

	// Transaction routes (dual auth with rate limiting)
	transactions := api.Group("/transactions")
	transactions.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	transactions.POST("", transactionHandler.CreateTransaction)
	transactions.GET("", transactionHandler.GetTransactions)
	transactions.GET("/categories/recent", transactionHandler.GetRecentlyUsedCategories)
	transactions.GET("/cc-metrics", transactionHandler.GetCCMetrics)
	transactions.PUT("/:id", transactionHandler.UpdateTransaction)
	transactions.DELETE("/:id", transactionHandler.DeleteTransaction)
	transactions.PATCH("/:id/toggle-paid", transactionHandler.TogglePaidStatus)
	transactions.PATCH("/:id/toggle-billed", transactionHandler.ToggleBilled)
	transactions.POST("/transfers", transactionHandler.CreateTransfer)
	transactions.POST("/batch-toggle-billed", transactionHandler.BatchToggleBilled)
	transactions.GET("/deferred-to-settle", transactionHandler.GetDeferredToSettle)
	transactions.GET("/overdue", transactionHandler.GetOverdue)
	transactions.PATCH("/:id/amount", transactionHandler.UpdateAmount)

	// Month routes (dual auth with rate limiting)
	months := api.Group("/months")
	months.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	months.GET("/current", monthHandler.GetCurrent)
	months.GET("/:year/:month", monthHandler.GetByYearMonth)
	months.GET("", monthHandler.GetAllMonths)

	// Dashboard routes (dual auth with rate limiting)
	dashboard := api.Group("/dashboard")
	dashboard.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	dashboard.GET("/summary", dashboardHandler.GetSummary)
	dashboard.GET("/future-spending", dashboardHandler.GetFutureSpending)

	// Budget Category routes (dual auth with rate limiting)
	budgetCategories := api.Group("/budget-categories")
	budgetCategories.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	budgetCategories.POST("", budgetCategoryHandler.CreateCategory)
	budgetCategories.GET("", budgetCategoryHandler.GetCategories)
	budgetCategories.PUT("/:id", budgetCategoryHandler.UpdateCategory)
	budgetCategories.DELETE("/:id", budgetCategoryHandler.DeleteCategory)
	budgetCategories.GET("/:id/can-delete", budgetCategoryHandler.CanDeleteCategory)

	// Budget Allocation routes (dual auth with rate limiting)
	budgets := api.Group("/budgets")
	budgets.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	budgets.GET("/:year/:month", budgetHandler.GetAllocations)
	budgets.PUT("/:year/:month", budgetHandler.SetAllocations)
	budgets.PUT("/:year/:month/:categoryId", budgetHandler.SetAllocation)
	budgets.GET("/:year/:month/:categoryId/transactions", budgetHandler.GetCategoryTransactions)

	// Credit Card routes (dual auth with rate limiting)
	cc := api.Group("/cc")
	cc.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	cc.POST("/payments", ccHandler.CreateCCPayment)

	// Settlement routes (dual auth with rate limiting)
	settlements := api.Group("/settlements")
	settlements.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	settlements.POST("", settlementHandler.Create)

	// Recurring Templates routes (dual auth with rate limiting)
	recurringTemplates := api.Group("/recurring-templates")
	recurringTemplates.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	recurringTemplates.POST("", recurringTemplateHandler.CreateTemplate)
	recurringTemplates.GET("", recurringTemplateHandler.ListTemplates)
	recurringTemplates.GET("/:id", recurringTemplateHandler.GetTemplate)
	recurringTemplates.PUT("/:id", recurringTemplateHandler.UpdateTemplate)
	recurringTemplates.DELETE("/:id", recurringTemplateHandler.DeleteTemplate)

	// Loan Provider routes (dual auth with rate limiting)
	loanProviders := api.Group("/loan-providers")
	loanProviders.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	loanProviders.POST("", loanProviderHandler.CreateLoanProvider)
	loanProviders.GET("", loanProviderHandler.GetLoanProviders)
	loanProviders.GET("/:id", loanProviderHandler.GetLoanProvider)
	loanProviders.PUT("/:id", loanProviderHandler.UpdateLoanProvider)
	loanProviders.DELETE("/:id", loanProviderHandler.DeleteLoanProvider)

	// Loan routes (dual auth with rate limiting)
	loans := api.Group("/loans")
	loans.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	loans.POST("", loanHandler.CreateLoan)
	loans.GET("", loanHandler.GetLoans)
	loans.POST("/preview", loanHandler.PreviewLoan)
	loans.GET("/commitments/:year/:month", loanHandler.GetMonthlyCommitments)
	loans.GET("/:id", loanHandler.GetLoan)
	loans.GET("/:id/delete-check", loanHandler.GetDeleteCheck)
	loans.PUT("/:id", loanHandler.UpdateLoan)
	loans.DELETE("/:id", loanHandler.DeleteLoan)

	// Loan Payment routes (nested under loans)
	loans.GET("/:loanId/payments", loanPaymentHandler.GetPaymentsByLoanID)
	loans.PATCH("/:loanId/payments/:paymentId", loanPaymentHandler.UpdatePaymentAmount)
	loans.PUT("/:loanId/payments/:paymentId/toggle-paid", loanPaymentHandler.TogglePaymentPaid)

	// Wishlist routes (dual auth with rate limiting)
	wishlists := api.Group("/wishlists")
	wishlists.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	wishlists.POST("", wishlistHandler.CreateWishlist)
	wishlists.GET("", wishlistHandler.GetWishlists)
	wishlists.GET("/:id", wishlistHandler.GetWishlist)
	wishlists.PUT("/:id", wishlistHandler.UpdateWishlist)
	wishlists.DELETE("/:id", wishlistHandler.DeleteWishlist)

	// Wishlist Item routes (nested under wishlists)
	wishlists.POST("/:id/items", wishlistItemHandler.CreateItem)
	wishlists.GET("/:id/items", wishlistItemHandler.ListItems)

	// Wishlist Item routes (direct access by item ID, dual auth with rate limiting)
	wishlistItems := api.Group("/wishlist-items")
	wishlistItems.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	wishlistItems.GET("/:id", wishlistItemHandler.GetItem)
	wishlistItems.PUT("/:id", wishlistItemHandler.UpdateItem)
	wishlistItems.PATCH("/:id/move", wishlistItemHandler.MoveItem)
	wishlistItems.DELETE("/:id", wishlistItemHandler.DeleteItem)

	// Wishlist Item Price routes (nested under wishlist-items)
	wishlistItems.POST("/:id/prices", wishlistPriceHandler.CreatePrice)
	wishlistItems.GET("/:id/prices", wishlistPriceHandler.ListPrices)
	wishlistItems.GET("/:id/prices/:platform", wishlistPriceHandler.GetPlatformHistory)

	// Wishlist Item Price routes (direct access by price ID, dual auth with rate limiting)
	wishlistItemPrices := api.Group("/wishlist-item-prices")
	wishlistItemPrices.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	wishlistItemPrices.DELETE("/:id", wishlistPriceHandler.DeletePrice)

	// Wishlist Item Note routes (nested under wishlist-items)
	wishlistItems.POST("/:id/notes", wishlistNoteHandler.CreateNote)
	wishlistItems.GET("/:id/notes", wishlistNoteHandler.ListNotes)

	// Wishlist Item Note routes (direct access by note ID, dual auth with rate limiting)
	wishlistItemNotes := api.Group("/wishlist-item-notes")
	wishlistItemNotes.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	wishlistItemNotes.GET("/:id", wishlistNoteHandler.GetNote)
	wishlistItemNotes.PUT("/:id", wishlistNoteHandler.UpdateNote)
	wishlistItemNotes.DELETE("/:id", wishlistNoteHandler.DeleteNote)

	// Image routes (binary uploads JWT only, presigned URLs support dual auth)
	images := api.Group("/images")
	images.Use(dualAuth.JWTOnly())
	images.POST("", imageHandler.UploadImage)
	images.DELETE("", imageHandler.DeleteImage)

	// Presigned URL routes (dual auth - usable by frontend and API tokens)
	presignedImages := api.Group("/images")
	presignedImages.Use(dualAuth.Authenticate(), middleware.RateLimitMiddleware(rateLimiter))
	presignedImages.GET("/url", imageHandler.GetPresignedURL)
	presignedImages.POST("/urls", imageHandler.GetBatchPresignedURLs)

	// API Token routes (JWT only - can't manage tokens with tokens)
	apiTokens := api.Group("/api-tokens")
	apiTokens.Use(dualAuth.JWTOnly())
	apiTokens.POST("", apiTokenHandler.CreateAPIToken)
	apiTokens.GET("", apiTokenHandler.GetAPITokens)
	apiTokens.DELETE("/:id", apiTokenHandler.RevokeAPIToken)
}
