// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (workspace_id, name, account_type, template, initial_balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, account_type, template, initial_balance, created_at, updated_at
`

type CreateAccountParams struct {
	WorkspaceID    int32          `json:"workspace_id"`
	Name           string         `json:"name"`
	AccountType    string         `json:"account_type"`
	Template       string         `json:"template"`
	InitialBalance pgtype.Numeric `json:"initial_balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.WorkspaceID,
		arg.Name,
		arg.AccountType,
		arg.Template,
		arg.InitialBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.AccountType,
		&i.Template,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, workspace_id, name, account_type, template, initial_balance, created_at, updated_at FROM accounts WHERE workspace_id = $1 AND id = $2
`

type GetAccountByIDParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.WorkspaceID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.AccountType,
		&i.Template,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByWorkspace = `-- name: GetAccountsByWorkspace :many
SELECT id, workspace_id, name, account_type, template, initial_balance, created_at, updated_at FROM accounts WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAccountsByWorkspace(ctx context.Context, workspaceID int32) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
