// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, workspace_id, description, token_hash, token_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, workspace_id, description, token_hash, token_prefix, last_used_at, created_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID int32       `json:"workspace_id"`
	Description string      `json:"description"`
	TokenHash   string      `json:"token_hash"`
	TokenPrefix string      `json:"token_prefix"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.WorkspaceID,
		arg.Description,
		arg.TokenHash,
		arg.TokenPrefix,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, workspace_id, description, token_hash, token_prefix, last_used_at, created_at, revoked_at FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT id, user_id, workspace_id, description, token_hash, token_prefix, last_used_at, created_at, revoked_at FROM api_tokens
WHERE workspace_id = $1 AND id = $2
`

type GetAPITokenByIDParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetAPITokenByID(ctx context.Context, arg GetAPITokenByIDParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, arg.WorkspaceID, arg.ID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokensByWorkspace = `-- name: GetAPITokensByWorkspace :many
SELECT id, user_id, workspace_id, description, token_hash, token_prefix, last_used_at, created_at, revoked_at FROM api_tokens
WHERE workspace_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAPITokensByWorkspace(ctx context.Context, workspaceID int32) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, getAPITokensByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Description,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}
