// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loan_payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoanPayment = `-- name: CreateLoanPayment :one
INSERT INTO loan_payments (
    loan_id,
    payment_number,
    amount,
    due_year,
    due_month,
    paid,
    paid_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at
`

type CreateLoanPaymentParams struct {
	LoanID        int32          `json:"loan_id"`
	PaymentNumber int32          `json:"payment_number"`
	Amount        pgtype.Numeric `json:"amount"`
	DueYear       int32          `json:"due_year"`
	DueMonth      int32          `json:"due_month"`
	Paid          bool           `json:"paid"`
	PaidDate      pgtype.Date    `json:"paid_date"`
}

func (q *Queries) CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, createLoanPayment,
		arg.LoanID,
		arg.PaymentNumber,
		arg.Amount,
		arg.DueYear,
		arg.DueMonth,
		arg.Paid,
		arg.PaidDate,
	)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentNumber,
		&i.Amount,
		&i.DueYear,
		&i.DueMonth,
		&i.Paid,
		&i.PaidDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanPaymentByID = `-- name: GetLoanPaymentByID :one
SELECT id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at FROM loan_payments
WHERE id = $1
`

func (q *Queries) GetLoanPaymentByID(ctx context.Context, id int32) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, getLoanPaymentByID, id)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentNumber,
		&i.Amount,
		&i.DueYear,
		&i.DueMonth,
		&i.Paid,
		&i.PaidDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanPaymentByLoanAndNumber = `-- name: GetLoanPaymentByLoanAndNumber :one
SELECT id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at FROM loan_payments
WHERE loan_id = $1 AND payment_number = $2
`

type GetLoanPaymentByLoanAndNumberParams struct {
	LoanID        int32 `json:"loan_id"`
	PaymentNumber int32 `json:"payment_number"`
}

func (q *Queries) GetLoanPaymentByLoanAndNumber(ctx context.Context, arg GetLoanPaymentByLoanAndNumberParams) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, getLoanPaymentByLoanAndNumber, arg.LoanID, arg.PaymentNumber)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentNumber,
		&i.Amount,
		&i.DueYear,
		&i.DueMonth,
		&i.Paid,
		&i.PaidDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanPaymentsByLoanID = `-- name: GetLoanPaymentsByLoanID :many
SELECT id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at FROM loan_payments
WHERE loan_id = $1
ORDER BY payment_number
`

func (q *Queries) GetLoanPaymentsByLoanID(ctx context.Context, loanID int32) ([]LoanPayment, error) {
	rows, err := q.db.Query(ctx, getLoanPaymentsByLoanID, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanPayment{}
	for rows.Next() {
		var i LoanPayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.PaymentNumber,
			&i.Amount,
			&i.DueYear,
			&i.DueMonth,
			&i.Paid,
			&i.PaidDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoanPaymentsByMonth = `-- name: GetLoanPaymentsByMonth :many
SELECT lp.id, lp.loan_id, lp.payment_number, lp.amount, lp.due_year, lp.due_month, lp.paid, lp.paid_date, lp.created_at, lp.updated_at FROM loan_payments lp
JOIN loans l ON lp.loan_id = l.id
WHERE l.workspace_id = $1
  AND lp.due_year = $2
  AND lp.due_month = $3
  AND l.deleted_at IS NULL
ORDER BY lp.due_year, lp.due_month, lp.payment_number
`

type GetLoanPaymentsByMonthParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	DueYear     int32 `json:"due_year"`
	DueMonth    int32 `json:"due_month"`
}

func (q *Queries) GetLoanPaymentsByMonth(ctx context.Context, arg GetLoanPaymentsByMonthParams) ([]LoanPayment, error) {
	rows, err := q.db.Query(ctx, getLoanPaymentsByMonth, arg.WorkspaceID, arg.DueYear, arg.DueMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanPayment{}
	for rows.Next() {
		var i LoanPayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.PaymentNumber,
			&i.Amount,
			&i.DueYear,
			&i.DueMonth,
			&i.Paid,
			&i.PaidDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpaidLoanPaymentsByMonth = `-- name: GetUnpaidLoanPaymentsByMonth :many
SELECT lp.id, lp.loan_id, lp.payment_number, lp.amount, lp.due_year, lp.due_month, lp.paid, lp.paid_date, lp.created_at, lp.updated_at FROM loan_payments lp
JOIN loans l ON lp.loan_id = l.id
WHERE l.workspace_id = $1
  AND lp.due_year = $2
  AND lp.due_month = $3
  AND lp.paid = FALSE
  AND l.deleted_at IS NULL
ORDER BY lp.due_year, lp.due_month, lp.payment_number
`

type GetUnpaidLoanPaymentsByMonthParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	DueYear     int32 `json:"due_year"`
	DueMonth    int32 `json:"due_month"`
}

func (q *Queries) GetUnpaidLoanPaymentsByMonth(ctx context.Context, arg GetUnpaidLoanPaymentsByMonthParams) ([]LoanPayment, error) {
	rows, err := q.db.Query(ctx, getUnpaidLoanPaymentsByMonth, arg.WorkspaceID, arg.DueYear, arg.DueMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanPayment{}
	for rows.Next() {
		var i LoanPayment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.PaymentNumber,
			&i.Amount,
			&i.DueYear,
			&i.DueMonth,
			&i.Paid,
			&i.PaidDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleLoanPaymentPaid = `-- name: ToggleLoanPaymentPaid :one
UPDATE loan_payments
SET paid = $2, paid_date = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at
`

type ToggleLoanPaymentPaidParams struct {
	ID       int32       `json:"id"`
	Paid     bool        `json:"paid"`
	PaidDate pgtype.Date `json:"paid_date"`
}

func (q *Queries) ToggleLoanPaymentPaid(ctx context.Context, arg ToggleLoanPaymentPaidParams) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, toggleLoanPaymentPaid, arg.ID, arg.Paid, arg.PaidDate)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentNumber,
		&i.Amount,
		&i.DueYear,
		&i.DueMonth,
		&i.Paid,
		&i.PaidDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoanPaymentAmount = `-- name: UpdateLoanPaymentAmount :one
UPDATE loan_payments
SET amount = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, loan_id, payment_number, amount, due_year, due_month, paid, paid_date, created_at, updated_at
`

type UpdateLoanPaymentAmountParams struct {
	ID     int32          `json:"id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) UpdateLoanPaymentAmount(ctx context.Context, arg UpdateLoanPaymentAmountParams) (LoanPayment, error) {
	row := q.db.QueryRow(ctx, updateLoanPaymentAmount, arg.ID, arg.Amount)
	var i LoanPayment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentNumber,
		&i.Amount,
		&i.DueYear,
		&i.DueMonth,
		&i.Paid,
		&i.PaidDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
