// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loan_providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoanProvider = `-- name: CreateLoanProvider :one
INSERT INTO loan_providers (
    workspace_id,
    name,
    cutoff_day,
    default_interest_rate
) VALUES (
    $1, $2, $3, $4
) RETURNING id, workspace_id, name, cutoff_day, default_interest_rate, created_at, updated_at, deleted_at, payment_mode
`

type CreateLoanProviderParams struct {
	WorkspaceID         int32          `json:"workspace_id"`
	Name                string         `json:"name"`
	CutoffDay           int32          `json:"cutoff_day"`
	DefaultInterestRate pgtype.Numeric `json:"default_interest_rate"`
}

func (q *Queries) CreateLoanProvider(ctx context.Context, arg CreateLoanProviderParams) (LoanProvider, error) {
	row := q.db.QueryRow(ctx, createLoanProvider,
		arg.WorkspaceID,
		arg.Name,
		arg.CutoffDay,
		arg.DefaultInterestRate,
	)
	var i LoanProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CutoffDay,
		&i.DefaultInterestRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentMode,
	)
	return i, err
}

const deleteLoanProvider = `-- name: DeleteLoanProvider :exec
UPDATE loan_providers
SET deleted_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type DeleteLoanProviderParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) DeleteLoanProvider(ctx context.Context, arg DeleteLoanProviderParams) error {
	_, err := q.db.Exec(ctx, deleteLoanProvider, arg.ID, arg.WorkspaceID)
	return err
}

const getLoanProviderByID = `-- name: GetLoanProviderByID :one
SELECT id, workspace_id, name, cutoff_day, default_interest_rate, created_at, updated_at, deleted_at, payment_mode FROM loan_providers
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetLoanProviderByIDParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetLoanProviderByID(ctx context.Context, arg GetLoanProviderByIDParams) (LoanProvider, error) {
	row := q.db.QueryRow(ctx, getLoanProviderByID, arg.ID, arg.WorkspaceID)
	var i LoanProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CutoffDay,
		&i.DefaultInterestRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentMode,
	)
	return i, err
}

const listLoanProviders = `-- name: ListLoanProviders :many
SELECT id, workspace_id, name, cutoff_day, default_interest_rate, created_at, updated_at, deleted_at, payment_mode FROM loan_providers
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListLoanProviders(ctx context.Context, workspaceID int32) ([]LoanProvider, error) {
	rows, err := q.db.Query(ctx, listLoanProviders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanProvider{}
	for rows.Next() {
		var i LoanProvider
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CutoffDay,
			&i.DefaultInterestRate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PaymentMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoanProvider = `-- name: UpdateLoanProvider :one
UPDATE loan_providers
SET
    name = $3,
    cutoff_day = $4,
    default_interest_rate = $5,
    payment_mode = COALESCE(NULLIF($6::text, ''), payment_mode),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, name, cutoff_day, default_interest_rate, created_at, updated_at, deleted_at, payment_mode
`

type UpdateLoanProviderParams struct {
	ID                  int32          `json:"id"`
	WorkspaceID         int32          `json:"workspace_id"`
	Name                string         `json:"name"`
	CutoffDay           int32          `json:"cutoff_day"`
	DefaultInterestRate pgtype.Numeric `json:"default_interest_rate"`
	PaymentMode         string         `json:"payment_mode"`
}

func (q *Queries) UpdateLoanProvider(ctx context.Context, arg UpdateLoanProviderParams) (LoanProvider, error) {
	row := q.db.QueryRow(ctx, updateLoanProvider,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.CutoffDay,
		arg.DefaultInterestRate,
		arg.PaymentMode,
	)
	var i LoanProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CutoffDay,
		&i.DefaultInterestRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentMode,
	)
	return i, err
}
