// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLoansByProvider = `-- name: CountActiveLoansByProvider :one
SELECT COUNT(*) FROM loans
WHERE provider_id = $1 AND workspace_id = $2 AND deleted_at IS NULL
  AND (
    (first_payment_year + ((first_payment_month - 1 + num_months - 1) / 12)) > $3
    OR (
      (first_payment_year + ((first_payment_month - 1 + num_months - 1) / 12)) = $3
      AND (((first_payment_month - 1 + num_months - 1) % 12) + 1) >= $4
    )
  )
`

type CountActiveLoansByProviderParams struct {
	ProviderID        int32 `json:"provider_id"`
	WorkspaceID       int32 `json:"workspace_id"`
	FirstPaymentYear  int32 `json:"first_payment_year"`
	FirstPaymentMonth int32 `json:"first_payment_month"`
}

func (q *Queries) CountActiveLoansByProvider(ctx context.Context, arg CountActiveLoansByProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLoansByProvider,
		arg.ProviderID,
		arg.WorkspaceID,
		arg.FirstPaymentYear,
		arg.FirstPaymentMonth,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (
    workspace_id,
    provider_id,
    item_name,
    total_amount,
    num_months,
    purchase_date,
    interest_rate,
    monthly_payment,
    first_payment_year,
    first_payment_month,
    account_id,
    settlement_intent,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent
`

type CreateLoanParams struct {
	WorkspaceID       int32          `json:"workspace_id"`
	ProviderID        int32          `json:"provider_id"`
	ItemName          string         `json:"item_name"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	NumMonths         int32          `json:"num_months"`
	PurchaseDate      pgtype.Date    `json:"purchase_date"`
	InterestRate      pgtype.Numeric `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric `json:"monthly_payment"`
	FirstPaymentYear  int32          `json:"first_payment_year"`
	FirstPaymentMonth int32          `json:"first_payment_month"`
	AccountID         pgtype.Int4    `json:"account_id"`
	SettlementIntent  pgtype.Text    `json:"settlement_intent"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.WorkspaceID,
		arg.ProviderID,
		arg.ItemName,
		arg.TotalAmount,
		arg.NumMonths,
		arg.PurchaseDate,
		arg.InterestRate,
		arg.MonthlyPayment,
		arg.FirstPaymentYear,
		arg.FirstPaymentMonth,
		arg.AccountID,
		arg.SettlementIntent,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.ItemName,
		&i.TotalAmount,
		&i.NumMonths,
		&i.PurchaseDate,
		&i.InterestRate,
		&i.MonthlyPayment,
		&i.FirstPaymentYear,
		&i.FirstPaymentMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.SettlementIntent,
	)
	return i, err
}

const deleteLoan = `-- name: DeleteLoan :exec
UPDATE loans
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type DeleteLoanParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) DeleteLoan(ctx context.Context, arg DeleteLoanParams) error {
	_, err := q.db.Exec(ctx, deleteLoan, arg.ID, arg.WorkspaceID)
	return err
}

const getActiveLoansWithStats = `-- name: GetActiveLoansWithStats :many
SELECT
    l.id,
    l.workspace_id,
    l.provider_id,
    l.item_name,
    l.total_amount,
    l.num_months,
    l.purchase_date,
    l.interest_rate,
    l.monthly_payment,
    l.first_payment_year,
    l.first_payment_month,
    l.account_id,
    l.settlement_intent,
    l.notes,
    l.created_at,
    l.updated_at,
    l.deleted_at,
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12))::INTEGER as last_payment_year,
    (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1)::INTEGER as last_payment_month,
    COUNT(t.id)::INTEGER as total_count,
    COUNT(t.id) FILTER (WHERE t.is_paid = true)::INTEGER as paid_count,
    COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0)::NUMERIC(12,2) as remaining_balance
FROM loans l
LEFT JOIN transactions t ON t.loan_id = l.id AND t.deleted_at IS NULL
WHERE l.workspace_id = $1 AND l.deleted_at IS NULL
GROUP BY l.id
HAVING COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0) > 0
ORDER BY l.created_at DESC
`

type GetActiveLoansWithStatsRow struct {
	ID                int32              `json:"id"`
	WorkspaceID       int32              `json:"workspace_id"`
	ProviderID        int32              `json:"provider_id"`
	ItemName          string             `json:"item_name"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	NumMonths         int32              `json:"num_months"`
	PurchaseDate      pgtype.Date        `json:"purchase_date"`
	InterestRate      pgtype.Numeric     `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric     `json:"monthly_payment"`
	FirstPaymentYear  int32              `json:"first_payment_year"`
	FirstPaymentMonth int32              `json:"first_payment_month"`
	AccountID         pgtype.Int4        `json:"account_id"`
	SettlementIntent  pgtype.Text        `json:"settlement_intent"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	LastPaymentYear   int32              `json:"last_payment_year"`
	LastPaymentMonth  int32              `json:"last_payment_month"`
	TotalCount        int32              `json:"total_count"`
	PaidCount         int32              `json:"paid_count"`
	RemainingBalance  pgtype.Numeric     `json:"remaining_balance"`
}

// Get active loans (with remaining balance) with payment stats calculated from transactions
func (q *Queries) GetActiveLoansWithStats(ctx context.Context, workspaceID int32) ([]GetActiveLoansWithStatsRow, error) {
	rows, err := q.db.Query(ctx, getActiveLoansWithStats, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveLoansWithStatsRow{}
	for rows.Next() {
		var i GetActiveLoansWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.AccountID,
			&i.SettlementIntent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastPaymentYear,
			&i.LastPaymentMonth,
			&i.TotalCount,
			&i.PaidCount,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedLoansWithStats = `-- name: GetCompletedLoansWithStats :many
SELECT
    l.id,
    l.workspace_id,
    l.provider_id,
    l.item_name,
    l.total_amount,
    l.num_months,
    l.purchase_date,
    l.interest_rate,
    l.monthly_payment,
    l.first_payment_year,
    l.first_payment_month,
    l.account_id,
    l.settlement_intent,
    l.notes,
    l.created_at,
    l.updated_at,
    l.deleted_at,
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12))::INTEGER as last_payment_year,
    (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1)::INTEGER as last_payment_month,
    COUNT(t.id)::INTEGER as total_count,
    COUNT(t.id) FILTER (WHERE t.is_paid = true)::INTEGER as paid_count,
    COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0)::NUMERIC(12,2) as remaining_balance
FROM loans l
LEFT JOIN transactions t ON t.loan_id = l.id AND t.deleted_at IS NULL
WHERE l.workspace_id = $1 AND l.deleted_at IS NULL
GROUP BY l.id
HAVING COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0) = 0
ORDER BY l.created_at DESC
`

type GetCompletedLoansWithStatsRow struct {
	ID                int32              `json:"id"`
	WorkspaceID       int32              `json:"workspace_id"`
	ProviderID        int32              `json:"provider_id"`
	ItemName          string             `json:"item_name"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	NumMonths         int32              `json:"num_months"`
	PurchaseDate      pgtype.Date        `json:"purchase_date"`
	InterestRate      pgtype.Numeric     `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric     `json:"monthly_payment"`
	FirstPaymentYear  int32              `json:"first_payment_year"`
	FirstPaymentMonth int32              `json:"first_payment_month"`
	AccountID         pgtype.Int4        `json:"account_id"`
	SettlementIntent  pgtype.Text        `json:"settlement_intent"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	LastPaymentYear   int32              `json:"last_payment_year"`
	LastPaymentMonth  int32              `json:"last_payment_month"`
	TotalCount        int32              `json:"total_count"`
	PaidCount         int32              `json:"paid_count"`
	RemainingBalance  pgtype.Numeric     `json:"remaining_balance"`
}

// Get completed loans (no remaining balance) with payment stats calculated from transactions
func (q *Queries) GetCompletedLoansWithStats(ctx context.Context, workspaceID int32) ([]GetCompletedLoansWithStatsRow, error) {
	rows, err := q.db.Query(ctx, getCompletedLoansWithStats, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletedLoansWithStatsRow{}
	for rows.Next() {
		var i GetCompletedLoansWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.AccountID,
			&i.SettlementIntent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastPaymentYear,
			&i.LastPaymentMonth,
			&i.TotalCount,
			&i.PaidCount,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent FROM loans
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetLoanByIDParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetLoanByID(ctx context.Context, arg GetLoanByIDParams) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, arg.ID, arg.WorkspaceID)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.ItemName,
		&i.TotalAmount,
		&i.NumMonths,
		&i.PurchaseDate,
		&i.InterestRate,
		&i.MonthlyPayment,
		&i.FirstPaymentYear,
		&i.FirstPaymentMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.SettlementIntent,
	)
	return i, err
}

const getLoansWithStats = `-- name: GetLoansWithStats :many

SELECT
    l.id,
    l.workspace_id,
    l.provider_id,
    l.item_name,
    l.total_amount,
    l.num_months,
    l.purchase_date,
    l.interest_rate,
    l.monthly_payment,
    l.first_payment_year,
    l.first_payment_month,
    l.account_id,
    l.settlement_intent,
    l.notes,
    l.created_at,
    l.updated_at,
    l.deleted_at,
    -- Calculated last payment month/year
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12))::INTEGER as last_payment_year,
    (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1)::INTEGER as last_payment_month,
    -- Payment stats from transactions
    COUNT(t.id)::INTEGER as total_count,
    COUNT(t.id) FILTER (WHERE t.is_paid = true)::INTEGER as paid_count,
    COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0)::NUMERIC(12,2) as remaining_balance
FROM loans l
LEFT JOIN transactions t ON t.loan_id = l.id AND t.deleted_at IS NULL
WHERE l.workspace_id = $1 AND l.deleted_at IS NULL
GROUP BY l.id
ORDER BY l.created_at DESC
`

type GetLoansWithStatsRow struct {
	ID                int32              `json:"id"`
	WorkspaceID       int32              `json:"workspace_id"`
	ProviderID        int32              `json:"provider_id"`
	ItemName          string             `json:"item_name"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	NumMonths         int32              `json:"num_months"`
	PurchaseDate      pgtype.Date        `json:"purchase_date"`
	InterestRate      pgtype.Numeric     `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric     `json:"monthly_payment"`
	FirstPaymentYear  int32              `json:"first_payment_year"`
	FirstPaymentMonth int32              `json:"first_payment_month"`
	AccountID         pgtype.Int4        `json:"account_id"`
	SettlementIntent  pgtype.Text        `json:"settlement_intent"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	LastPaymentYear   int32              `json:"last_payment_year"`
	LastPaymentMonth  int32              `json:"last_payment_month"`
	TotalCount        int32              `json:"total_count"`
	PaidCount         int32              `json:"paid_count"`
	RemainingBalance  pgtype.Numeric     `json:"remaining_balance"`
}

// CL v2: Use transactions with loan_id instead of loan_payments table
// Get all loans with payment stats calculated from transactions
func (q *Queries) GetLoansWithStats(ctx context.Context, workspaceID int32) ([]GetLoansWithStatsRow, error) {
	rows, err := q.db.Query(ctx, getLoansWithStats, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLoansWithStatsRow{}
	for rows.Next() {
		var i GetLoansWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.AccountID,
			&i.SettlementIntent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastPaymentYear,
			&i.LastPaymentMonth,
			&i.TotalCount,
			&i.PaidCount,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoansWithStatsByProvider = `-- name: GetLoansWithStatsByProvider :many
SELECT
    l.id,
    l.workspace_id,
    l.provider_id,
    l.item_name,
    l.total_amount,
    l.num_months,
    l.purchase_date,
    l.interest_rate,
    l.monthly_payment,
    l.first_payment_year,
    l.first_payment_month,
    l.account_id,
    l.settlement_intent,
    l.notes,
    l.created_at,
    l.updated_at,
    l.deleted_at,
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12))::INTEGER as last_payment_year,
    (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1)::INTEGER as last_payment_month,
    COUNT(t.id)::INTEGER as total_count,
    COUNT(t.id) FILTER (WHERE t.is_paid = true)::INTEGER as paid_count,
    COALESCE(SUM(t.amount) FILTER (WHERE t.is_paid = false), 0)::NUMERIC(12,2) as remaining_balance
FROM loans l
LEFT JOIN transactions t ON t.loan_id = l.id AND t.deleted_at IS NULL
WHERE l.workspace_id = $1 AND l.provider_id = $2 AND l.deleted_at IS NULL
GROUP BY l.id
ORDER BY (COUNT(t.id) FILTER (WHERE t.is_paid = false) > 0) DESC, l.item_name ASC
`

type GetLoansWithStatsByProviderParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ProviderID  int32 `json:"provider_id"`
}

type GetLoansWithStatsByProviderRow struct {
	ID                int32              `json:"id"`
	WorkspaceID       int32              `json:"workspace_id"`
	ProviderID        int32              `json:"provider_id"`
	ItemName          string             `json:"item_name"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	NumMonths         int32              `json:"num_months"`
	PurchaseDate      pgtype.Date        `json:"purchase_date"`
	InterestRate      pgtype.Numeric     `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric     `json:"monthly_payment"`
	FirstPaymentYear  int32              `json:"first_payment_year"`
	FirstPaymentMonth int32              `json:"first_payment_month"`
	AccountID         pgtype.Int4        `json:"account_id"`
	SettlementIntent  pgtype.Text        `json:"settlement_intent"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	LastPaymentYear   int32              `json:"last_payment_year"`
	LastPaymentMonth  int32              `json:"last_payment_month"`
	TotalCount        int32              `json:"total_count"`
	PaidCount         int32              `json:"paid_count"`
	RemainingBalance  pgtype.Numeric     `json:"remaining_balance"`
}

// Get all loans for a specific provider with payment stats calculated from transactions
// Orders unpaid items first, then by item name
func (q *Queries) GetLoansWithStatsByProvider(ctx context.Context, arg GetLoansWithStatsByProviderParams) ([]GetLoansWithStatsByProviderRow, error) {
	rows, err := q.db.Query(ctx, getLoansWithStatsByProvider, arg.WorkspaceID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLoansWithStatsByProviderRow{}
	for rows.Next() {
		var i GetLoansWithStatsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.AccountID,
			&i.SettlementIntent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastPaymentYear,
			&i.LastPaymentMonth,
			&i.TotalCount,
			&i.PaidCount,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLoans = `-- name: ListActiveLoans :many
SELECT l.id, l.workspace_id, l.provider_id, l.item_name, l.total_amount, l.num_months, l.purchase_date, l.interest_rate, l.monthly_payment, l.first_payment_year, l.first_payment_month, l.notes, l.created_at, l.updated_at, l.deleted_at, l.account_id, l.settlement_intent FROM loans l
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  AND (
    -- Loan is active if there are remaining payments
    -- Current month is before or equal to last payment month
    -- last_payment_year = first_payment_year + (num_months - 1) / 12
    -- last_payment_month = ((first_payment_month - 1 + num_months - 1) % 12) + 1
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12)) > $2
    OR (
      (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12)) = $2
      AND (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1) >= $3
    )
  )
ORDER BY l.created_at DESC
`

type ListActiveLoansParams struct {
	WorkspaceID       int32 `json:"workspace_id"`
	FirstPaymentYear  int32 `json:"first_payment_year"`
	FirstPaymentMonth int32 `json:"first_payment_month"`
}

func (q *Queries) ListActiveLoans(ctx context.Context, arg ListActiveLoansParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listActiveLoans, arg.WorkspaceID, arg.FirstPaymentYear, arg.FirstPaymentMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountID,
			&i.SettlementIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedLoans = `-- name: ListCompletedLoans :many
SELECT l.id, l.workspace_id, l.provider_id, l.item_name, l.total_amount, l.num_months, l.purchase_date, l.interest_rate, l.monthly_payment, l.first_payment_year, l.first_payment_month, l.notes, l.created_at, l.updated_at, l.deleted_at, l.account_id, l.settlement_intent FROM loans l
WHERE l.workspace_id = $1
  AND l.deleted_at IS NULL
  AND (
    -- Loan is completed if current month is past the last payment month
    (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12)) < $2
    OR (
      (l.first_payment_year + ((l.first_payment_month - 1 + l.num_months - 1) / 12)) = $2
      AND (((l.first_payment_month - 1 + l.num_months - 1) % 12) + 1) < $3
    )
  )
ORDER BY l.created_at DESC
`

type ListCompletedLoansParams struct {
	WorkspaceID       int32 `json:"workspace_id"`
	FirstPaymentYear  int32 `json:"first_payment_year"`
	FirstPaymentMonth int32 `json:"first_payment_month"`
}

func (q *Queries) ListCompletedLoans(ctx context.Context, arg ListCompletedLoansParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listCompletedLoans, arg.WorkspaceID, arg.FirstPaymentYear, arg.FirstPaymentMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountID,
			&i.SettlementIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoans = `-- name: ListLoans :many
SELECT id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent FROM loans
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLoans(ctx context.Context, workspaceID int32) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoans, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProviderID,
			&i.ItemName,
			&i.TotalAmount,
			&i.NumMonths,
			&i.PurchaseDate,
			&i.InterestRate,
			&i.MonthlyPayment,
			&i.FirstPaymentYear,
			&i.FirstPaymentMonth,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountID,
			&i.SettlementIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoan = `-- name: UpdateLoan :one
UPDATE loans
SET item_name = $3,
    total_amount = $4,
    num_months = $5,
    purchase_date = $6,
    interest_rate = $7,
    monthly_payment = $8,
    first_payment_year = $9,
    first_payment_month = $10,
    notes = $11,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent
`

type UpdateLoanParams struct {
	ID                int32          `json:"id"`
	WorkspaceID       int32          `json:"workspace_id"`
	ItemName          string         `json:"item_name"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	NumMonths         int32          `json:"num_months"`
	PurchaseDate      pgtype.Date    `json:"purchase_date"`
	InterestRate      pgtype.Numeric `json:"interest_rate"`
	MonthlyPayment    pgtype.Numeric `json:"monthly_payment"`
	FirstPaymentYear  int32          `json:"first_payment_year"`
	FirstPaymentMonth int32          `json:"first_payment_month"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoan,
		arg.ID,
		arg.WorkspaceID,
		arg.ItemName,
		arg.TotalAmount,
		arg.NumMonths,
		arg.PurchaseDate,
		arg.InterestRate,
		arg.MonthlyPayment,
		arg.FirstPaymentYear,
		arg.FirstPaymentMonth,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.ItemName,
		&i.TotalAmount,
		&i.NumMonths,
		&i.PurchaseDate,
		&i.InterestRate,
		&i.MonthlyPayment,
		&i.FirstPaymentYear,
		&i.FirstPaymentMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.SettlementIntent,
	)
	return i, err
}

const updateLoanEditableFields = `-- name: UpdateLoanEditableFields :one
UPDATE loans
SET item_name = $3,
    provider_id = $4,
    notes = $5,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent
`

type UpdateLoanEditableFieldsParams struct {
	ID          int32       `json:"id"`
	WorkspaceID int32       `json:"workspace_id"`
	ItemName    string      `json:"item_name"`
	ProviderID  int32       `json:"provider_id"`
	Notes       pgtype.Text `json:"notes"`
}

// Updates editable fields with optional provider change
// Provider can only change if no payments have been made (validated at service layer)
func (q *Queries) UpdateLoanEditableFields(ctx context.Context, arg UpdateLoanEditableFieldsParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanEditableFields,
		arg.ID,
		arg.WorkspaceID,
		arg.ItemName,
		arg.ProviderID,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.ItemName,
		&i.TotalAmount,
		&i.NumMonths,
		&i.PurchaseDate,
		&i.InterestRate,
		&i.MonthlyPayment,
		&i.FirstPaymentYear,
		&i.FirstPaymentMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.SettlementIntent,
	)
	return i, err
}

const updateLoanPartial = `-- name: UpdateLoanPartial :one
UPDATE loans
SET item_name = $3,
    notes = $4,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, provider_id, item_name, total_amount, num_months, purchase_date, interest_rate, monthly_payment, first_payment_year, first_payment_month, notes, created_at, updated_at, deleted_at, account_id, settlement_intent
`

type UpdateLoanPartialParams struct {
	ID          int32       `json:"id"`
	WorkspaceID int32       `json:"workspace_id"`
	ItemName    string      `json:"item_name"`
	Notes       pgtype.Text `json:"notes"`
}

// Only updates editable fields (item_name, notes) - amount/months/dates are locked after creation
func (q *Queries) UpdateLoanPartial(ctx context.Context, arg UpdateLoanPartialParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanPartial,
		arg.ID,
		arg.WorkspaceID,
		arg.ItemName,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProviderID,
		&i.ItemName,
		&i.TotalAmount,
		&i.NumMonths,
		&i.PurchaseDate,
		&i.InterestRate,
		&i.MonthlyPayment,
		&i.FirstPaymentYear,
		&i.FirstPaymentMonth,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AccountID,
		&i.SettlementIntent,
	)
	return i, err
}
