// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             int32              `json:"id"`
	WorkspaceID    int32              `json:"workspace_id"`
	Name           string             `json:"name"`
	AccountType    string             `json:"account_type"`
	Template       string             `json:"template"`
	InitialBalance pgtype.Numeric     `json:"initial_balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type BudgetAllocation struct {
	ID          int32              `json:"id"`
	WorkspaceID int32              `json:"workspace_id"`
	CategoryID  int32              `json:"category_id"`
	Year        int32              `json:"year"`
	Month       int32              `json:"month"`
	Amount      pgtype.Numeric     `json:"amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BudgetCategory struct {
	ID          int32              `json:"id"`
	WorkspaceID int32              `json:"workspace_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Month struct {
	ID              int32              `json:"id"`
	WorkspaceID     int32              `json:"workspace_id"`
	Year            int32              `json:"year"`
	Month           int32              `json:"month"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	StartingBalance pgtype.Numeric     `json:"starting_balance"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RecurringTransaction struct {
	ID          int32              `json:"id"`
	WorkspaceID int32              `json:"workspace_id"`
	Name        string             `json:"name"`
	Amount      pgtype.Numeric     `json:"amount"`
	AccountID   int32              `json:"account_id"`
	Type        string             `json:"type"`
	CategoryID  pgtype.Int4        `json:"category_id"`
	Frequency   string             `json:"frequency"`
	DueDay      int32              `json:"due_day"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Transaction struct {
	ID                 int32              `json:"id"`
	WorkspaceID        int32              `json:"workspace_id"`
	AccountID          int32              `json:"account_id"`
	Name               string             `json:"name"`
	Amount             pgtype.Numeric     `json:"amount"`
	Type               string             `json:"type"`
	TransactionDate    pgtype.Date        `json:"transaction_date"`
	IsPaid             bool               `json:"is_paid"`
	CcSettlementIntent pgtype.Text        `json:"cc_settlement_intent"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID     pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID         pgtype.Int4        `json:"category_id"`
	IsCcPayment        bool               `json:"is_cc_payment"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	Auth0ID    string             `json:"auth0_id"`
	Email      string             `json:"email"`
	Name       pgtype.Text        `json:"name"`
	PictureUrl pgtype.Text        `json:"picture_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
