// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             int32              `json:"id"`
	WorkspaceID    int32              `json:"workspace_id"`
	Name           string             `json:"name"`
	AccountType    string             `json:"account_type"`
	Template       string             `json:"template"`
	InitialBalance pgtype.Numeric     `json:"initial_balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	Auth0ID    string             `json:"auth0_id"`
	Email      string             `json:"email"`
	Name       pgtype.Text        `json:"name"`
	PictureUrl pgtype.Text        `json:"picture_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
