// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: months.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonth = `-- name: CreateMonth :one
INSERT INTO months (workspace_id, year, month, start_date, end_date, starting_balance)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, year, month, start_date, end_date, starting_balance, created_at, updated_at
`

type CreateMonthParams struct {
	WorkspaceID     int32          `json:"workspace_id"`
	Year            int32          `json:"year"`
	Month           int32          `json:"month"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	StartingBalance pgtype.Numeric `json:"starting_balance"`
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error) {
	row := q.db.QueryRow(ctx, createMonth,
		arg.WorkspaceID,
		arg.Year,
		arg.Month,
		arg.StartDate,
		arg.EndDate,
		arg.StartingBalance,
	)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.StartDate,
		&i.EndDate,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllMonths = `-- name: GetAllMonths :many
SELECT id, workspace_id, year, month, start_date, end_date, starting_balance, created_at, updated_at FROM months
WHERE workspace_id = $1
ORDER BY year DESC, month DESC
`

func (q *Queries) GetAllMonths(ctx context.Context, workspaceID int32) ([]Month, error) {
	rows, err := q.db.Query(ctx, getAllMonths, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Month{}
	for rows.Next() {
		var i Month
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Year,
			&i.Month,
			&i.StartDate,
			&i.EndDate,
			&i.StartingBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMonth = `-- name: GetLatestMonth :one
SELECT id, workspace_id, year, month, start_date, end_date, starting_balance, created_at, updated_at FROM months
WHERE workspace_id = $1
ORDER BY year DESC, month DESC
LIMIT 1
`

func (q *Queries) GetLatestMonth(ctx context.Context, workspaceID int32) (Month, error) {
	row := q.db.QueryRow(ctx, getLatestMonth, workspaceID)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.StartDate,
		&i.EndDate,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthByYearMonth = `-- name: GetMonthByYearMonth :one
SELECT id, workspace_id, year, month, start_date, end_date, starting_balance, created_at, updated_at FROM months
WHERE workspace_id = $1 AND year = $2 AND month = $3
`

type GetMonthByYearMonthParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	Year        int32 `json:"year"`
	Month       int32 `json:"month"`
}

func (q *Queries) GetMonthByYearMonth(ctx context.Context, arg GetMonthByYearMonthParams) (Month, error) {
	row := q.db.QueryRow(ctx, getMonthByYearMonth, arg.WorkspaceID, arg.Year, arg.Month)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.StartDate,
		&i.EndDate,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonthStartingBalance = `-- name: UpdateMonthStartingBalance :exec
UPDATE months
SET starting_balance = $3, updated_at = NOW()
WHERE workspace_id = $1 AND id = $2
`

type UpdateMonthStartingBalanceParams struct {
	WorkspaceID     int32          `json:"workspace_id"`
	ID              int32          `json:"id"`
	StartingBalance pgtype.Numeric `json:"starting_balance"`
}

func (q *Queries) UpdateMonthStartingBalance(ctx context.Context, arg UpdateMonthStartingBalanceParams) error {
	_, err := q.db.Exec(ctx, updateMonthStartingBalance, arg.WorkspaceID, arg.ID, arg.StartingBalance)
	return err
}
