// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Check if a transaction already exists for a recurring template in a specific month
	CheckRecurringTransactionExists(ctx context.Context, arg CheckRecurringTransactionExistsParams) (int32, error)
	// Copies all allocations from one month to another (atomic, skips deleted categories)
	CopyAllocationsToMonth(ctx context.Context, arg CopyAllocationsToMonthParams) error
	CountActiveLoansByProvider(ctx context.Context, arg CountActiveLoansByProviderParams) (int64, error)
	// Returns the count of allocations for a specific month (for lazy initialization check)
	CountAllocationsForMonth(ctx context.Context, arg CountAllocationsForMonthParams) (int64, error)
	// Count transactions assigned to a specific category
	CountTransactionsByCategory(ctx context.Context, arg CountTransactionsByCategoryParams) (int64, error)
	CountTransactionsByWorkspace(ctx context.Context, arg CountTransactionsByWorkspaceParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudgetCategory(ctx context.Context, arg CreateBudgetCategoryParams) (BudgetCategory, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error)
	CreateLoanProvider(ctx context.Context, arg CreateLoanProviderParams) (LoanProvider, error)
	CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error)
	CreateOrGetUserByAuth0ID(ctx context.Context, arg CreateOrGetUserByAuth0IDParams) (User, error)
	CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteBudgetAllocation(ctx context.Context, arg DeleteBudgetAllocationParams) error
	DeleteLoan(ctx context.Context, arg DeleteLoanParams) error
	DeleteLoanProvider(ctx context.Context, arg DeleteLoanProviderParams) error
	DeleteWorkspace(ctx context.Context, id int32) error
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAccountByIDIncludeDeleted(ctx context.Context, arg GetAccountByIDIncludeDeletedParams) (Account, error)
	GetAccountTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetAccountTransactionSummariesRow, error)
	GetAccountsByWorkspace(ctx context.Context, workspaceID int32) ([]Account, error)
	GetAccountsByWorkspaceAll(ctx context.Context, workspaceID int32) ([]Account, error)
	GetActiveLoansWithStats(ctx context.Context, workspaceID int32) ([]GetActiveLoansWithStatsRow, error)
	GetAllBudgetCategories(ctx context.Context, workspaceID int32) ([]BudgetCategory, error)
	GetAllMonths(ctx context.Context, workspaceID int32) ([]Month, error)
	GetBudgetAllocationByCategory(ctx context.Context, arg GetBudgetAllocationByCategoryParams) (BudgetAllocation, error)
	GetBudgetAllocationsByMonth(ctx context.Context, arg GetBudgetAllocationsByMonthParams) ([]GetBudgetAllocationsByMonthRow, error)
	GetBudgetCategoryByID(ctx context.Context, arg GetBudgetCategoryByIDParams) (BudgetCategory, error)
	GetBudgetCategoryByName(ctx context.Context, arg GetBudgetCategoryByNameParams) (BudgetCategory, error)
	// Get total outstanding balance across all CC accounts (sum of unpaid expenses)
	GetCCOutstandingSummary(ctx context.Context, workspaceID int32) (GetCCOutstandingSummaryRow, error)
	// Get all unpaid CC transactions with settlement intent for payable breakdown
	GetCCPayableBreakdown(ctx context.Context, workspaceID int32) ([]GetCCPayableBreakdownRow, error)
	// Get unpaid CC transaction totals grouped by settlement intent
	GetCCPayableSummary(ctx context.Context, workspaceID int32) ([]GetCCPayableSummaryRow, error)
	// Returns all categories with their allocation for a specific month (0 if not set)
	GetCategoriesWithAllocations(ctx context.Context, arg GetCategoriesWithAllocationsParams) ([]GetCategoriesWithAllocationsRow, error)
	// Returns all transactions for a specific category in a month
	GetCategoryTransactions(ctx context.Context, arg GetCategoryTransactionsParams) ([]GetCategoryTransactionsRow, error)
	GetCompletedLoansWithStats(ctx context.Context, workspaceID int32) ([]GetCompletedLoansWithStatsRow, error)
	GetLatestMonth(ctx context.Context, workspaceID int32) (Month, error)
	GetLoanByID(ctx context.Context, arg GetLoanByIDParams) (Loan, error)
	GetLoanPaymentByID(ctx context.Context, id int32) (LoanPayment, error)
	GetLoanPaymentByLoanAndNumber(ctx context.Context, arg GetLoanPaymentByLoanAndNumberParams) (LoanPayment, error)
	GetLoanPaymentsByLoanID(ctx context.Context, loanID int32) ([]LoanPayment, error)
	GetLoanPaymentsByMonth(ctx context.Context, arg GetLoanPaymentsByMonthParams) ([]LoanPayment, error)
	GetLoanProviderByID(ctx context.Context, arg GetLoanProviderByIDParams) (LoanProvider, error)
	GetLoansWithStats(ctx context.Context, workspaceID int32) ([]GetLoansWithStatsRow, error)
	GetMonthByYearMonth(ctx context.Context, arg GetMonthByYearMonthParams) (Month, error)
	// Batch query to get income/expense totals grouped by year/month for N+1 prevention
	GetMonthlyTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetMonthlyTransactionSummariesRow, error)
	// Get outstanding balance for each CC account
	GetPerAccountOutstanding(ctx context.Context, workspaceID int32) ([]GetPerAccountOutstandingRow, error)
	// Returns recently used categories for suggestions dropdown
	GetRecentlyUsedCategories(ctx context.Context, workspaceID int32) ([]GetRecentlyUsedCategoriesRow, error)
	GetRecurringTransaction(ctx context.Context, arg GetRecurringTransactionParams) (RecurringTransaction, error)
	// Returns total spending per category for a specific month
	GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	GetTransactionsByWorkspace(ctx context.Context, arg GetTransactionsByWorkspaceParams) ([]Transaction, error)
	// Returns transactions with category name joined for display
	GetTransactionsWithCategory(ctx context.Context, arg GetTransactionsWithCategoryParams) ([]GetTransactionsWithCategoryRow, error)
	GetUnpaidLoanPaymentsByMonth(ctx context.Context, arg GetUnpaidLoanPaymentsByMonthParams) ([]LoanPayment, error)
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id int32) (Workspace, error)
	GetWorkspaceByUserAuth0ID(ctx context.Context, auth0ID string) (Workspace, error)
	GetWorkspaceByUserID(ctx context.Context, userID pgtype.UUID) (Workspace, error)
	HardDeleteAccount(ctx context.Context, arg HardDeleteAccountParams) error
	ListActiveLoans(ctx context.Context, arg ListActiveLoansParams) ([]Loan, error)
	ListCompletedLoans(ctx context.Context, arg ListCompletedLoansParams) ([]Loan, error)
	ListLoanProviders(ctx context.Context, workspaceID int32) ([]LoanProvider, error)
	ListLoans(ctx context.Context, workspaceID int32) ([]Loan, error)
	ListRecurringTransactions(ctx context.Context, arg ListRecurringTransactionsParams) ([]RecurringTransaction, error)
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (int64, error)
	SoftDeleteBudgetCategory(ctx context.Context, arg SoftDeleteBudgetCategoryParams) error
	SoftDeleteRecurringTransaction(ctx context.Context, arg SoftDeleteRecurringTransactionParams) (int64, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error)
	SoftDeleteTransferPair(ctx context.Context, arg SoftDeleteTransferPairParams) (int64, error)
	// Sum paid expenses within a date range for in-hand balance calculation
	SumPaidExpensesByDateRange(ctx context.Context, arg SumPaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	SumTransactionsByTypeAndDateRange(ctx context.Context, arg SumTransactionsByTypeAndDateRangeParams) (pgtype.Numeric, error)
	// Sum unpaid expenses within a date range for disposable income calculation
	SumUnpaidExpensesByDateRange(ctx context.Context, arg SumUnpaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	ToggleLoanPaymentPaid(ctx context.Context, arg ToggleLoanPaymentPaidParams) (LoanPayment, error)
	ToggleTransactionPaidStatus(ctx context.Context, arg ToggleTransactionPaidStatusParams) (Transaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudgetCategory(ctx context.Context, arg UpdateBudgetCategoryParams) (BudgetCategory, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	UpdateLoanPaymentAmount(ctx context.Context, arg UpdateLoanPaymentAmountParams) (LoanPayment, error)
	UpdateLoanProvider(ctx context.Context, arg UpdateLoanProviderParams) (LoanProvider, error)
	UpdateMonthStartingBalance(ctx context.Context, arg UpdateMonthStartingBalanceParams) error
	UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateTransactionSettlementIntent(ctx context.Context, arg UpdateTransactionSettlementIntentParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertBudgetAllocation(ctx context.Context, arg UpsertBudgetAllocationParams) (BudgetAllocation, error)
}

var _ Querier = (*Queries)(nil)
