// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignGroupToTransactions(ctx context.Context, arg AssignGroupToTransactionsParams) error
	// Bulk mark loan transactions as paid by IDs with timestamp
	BatchMarkLoanTransactionsPaid(ctx context.Context, arg BatchMarkLoanTransactionsPaidParams) ([]Transaction, error)
	// Bulk mark loan transactions as unpaid by IDs
	BatchMarkLoanTransactionsUnpaid(ctx context.Context, arg BatchMarkLoanTransactionsUnpaidParams) ([]Transaction, error)
	// Batch toggle multiple transactions from pending to billed
	BatchToggleToBilled(ctx context.Context, arg BatchToggleToBilledParams) ([]Transaction, error)
	// Bulk mark transactions as paid by IDs (works for both bank and CC transactions)
	// For CC transactions, this also effectively sets cc_state to 'settled' since it's computed from is_paid
	BulkMarkTransactionsPaid(ctx context.Context, arg BulkMarkTransactionsPaidParams) ([]Transaction, error)
	// Bulk update multiple transactions to settled state (is_paid = true)
	BulkSettleTransactions(ctx context.Context, arg BulkSettleTransactionsParams) ([]Transaction, error)
	// Copies all allocations from one month to another (atomic, skips deleted categories)
	CopyAllocationsToMonth(ctx context.Context, arg CopyAllocationsToMonthParams) error
	CountActiveLoansByProvider(ctx context.Context, arg CountActiveLoansByProviderParams) (int64, error)
	// Returns the count of allocations for a specific month (for lazy initialization check)
	CountAllocationsForMonth(ctx context.Context, arg CountAllocationsForMonthParams) (int64, error)
	CountGroupChildren(ctx context.Context, arg CountGroupChildrenParams) (int32, error)
	CountNotesByItem(ctx context.Context, arg CountNotesByItemParams) (int64, error)
	// Count transactions assigned to a specific category
	CountTransactionsByCategory(ctx context.Context, arg CountTransactionsByCategoryParams) (int64, error)
	CountTransactionsByWorkspace(ctx context.Context, arg CountTransactionsByWorkspaceParams) (int64, error)
	CountWishlistItems(ctx context.Context, arg CountWishlistItemsParams) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudgetCategory(ctx context.Context, arg CreateBudgetCategoryParams) (BudgetCategory, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (TransactionGroup, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLoanProvider(ctx context.Context, arg CreateLoanProviderParams) (LoanProvider, error)
	CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error)
	CreateOrGetUserByAuth0ID(ctx context.Context, arg CreateOrGetUserByAuth0IDParams) (User, error)
	CreateProjectionExclusion(ctx context.Context, arg CreateProjectionExclusionParams) error
	// Recurring Templates (recurring_templates table)
	CreateRecurringTemplate(ctx context.Context, arg CreateRecurringTemplateParams) (RecurringTemplate, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWishlist(ctx context.Context, arg CreateWishlistParams) (Wishlist, error)
	CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error)
	CreateWishlistItemNote(ctx context.Context, arg CreateWishlistItemNoteParams) (WishlistItemNote, error)
	CreateWishlistItemPrice(ctx context.Context, arg CreateWishlistItemPriceParams) (WishlistItemPrice, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteBudgetAllocation(ctx context.Context, arg DeleteBudgetAllocationParams) error
	DeleteExclusionsByTemplate(ctx context.Context, templateID int32) error
	DeleteGroup(ctx context.Context, arg DeleteGroupParams) error
	DeleteLoan(ctx context.Context, arg DeleteLoanParams) error
	DeleteLoanProvider(ctx context.Context, arg DeleteLoanProviderParams) error
	// Delete projections beyond a specific date (used when changing template end_date)
	DeleteProjectionsBeyondDate(ctx context.Context, arg DeleteProjectionsBeyondDateParams) error
	// Delete unpaid projected transactions for a template (used when deleting template)
	// Paid projections are preserved and orphaned instead
	DeleteProjectionsByTemplate(ctx context.Context, arg DeleteProjectionsByTemplateParams) error
	DeleteRecurringTemplate(ctx context.Context, arg DeleteRecurringTemplateParams) error
	// Hard delete unpaid transactions for a loan
	// Used when deleting a loan (unpaid future payments are removed)
	DeleteUnpaidTransactionsByLoan(ctx context.Context, arg DeleteUnpaidTransactionsByLoanParams) error
	DeleteWishlist(ctx context.Context, arg DeleteWishlistParams) error
	DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error
	DeleteWishlistItemNote(ctx context.Context, arg DeleteWishlistItemNoteParams) error
	DeleteWishlistItemPrice(ctx context.Context, arg DeleteWishlistItemPriceParams) error
	DeleteWorkspace(ctx context.Context, id int32) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, arg GetAPITokenByIDParams) (ApiToken, error)
	GetAPITokensByWorkspace(ctx context.Context, workspaceID int32) ([]ApiToken, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAccountByIDIncludeDeleted(ctx context.Context, arg GetAccountByIDIncludeDeletedParams) (Account, error)
	// For regular accounts: only count paid transactions
	// For CC accounts: count all expenses (isPaid means settled, not whether purchase happened)
	GetAccountTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetAccountTransactionSummariesRow, error)
	GetAccountsByWorkspace(ctx context.Context, workspaceID int32) ([]Account, error)
	GetAccountsByWorkspaceAll(ctx context.Context, workspaceID int32) ([]Account, error)
	// Get active loans (with remaining balance) with payment stats calculated from transactions
	GetActiveLoansWithStats(ctx context.Context, workspaceID int32) ([]GetActiveLoansWithStatsRow, error)
	GetActiveRecurringTemplates(ctx context.Context, workspaceID int32) ([]RecurringTemplate, error)
	// Get all active templates across all workspaces (for daily sync goroutine)
	GetAllActiveTemplates(ctx context.Context) ([]RecurringTemplate, error)
	GetAllBudgetCategories(ctx context.Context, workspaceID int32) ([]BudgetCategory, error)
	GetAllMonths(ctx context.Context, workspaceID int32) ([]Month, error)
	GetAutoDetectedGroupByProviderMonth(ctx context.Context, arg GetAutoDetectedGroupByProviderMonthParams) (GetAutoDetectedGroupByProviderMonthRow, error)
	GetBestPriceForItem(ctx context.Context, arg GetBestPriceForItemParams) (string, error)
	// Get billed CC transactions with deferred settlement intent for a month range
	GetBilledCCByMonth(ctx context.Context, arg GetBilledCCByMonthParams) ([]GetBilledCCByMonthRow, error)
	GetBudgetAllocationByCategory(ctx context.Context, arg GetBudgetAllocationByCategoryParams) (BudgetAllocation, error)
	GetBudgetAllocationsByMonth(ctx context.Context, arg GetBudgetAllocationsByMonthParams) ([]GetBudgetAllocationsByMonthRow, error)
	GetBudgetCategoryByID(ctx context.Context, arg GetBudgetCategoryByIDParams) (BudgetCategory, error)
	GetBudgetCategoryByName(ctx context.Context, arg GetBudgetCategoryByNameParams) (BudgetCategory, error)
	// Get CC metrics (pending, outstanding, purchases) for a month range
	// Simplified: pending = billed_at IS NULL, billed = billed_at IS NOT NULL AND is_paid = false, settled = is_paid = true
	// purchases = CC expenses this month (EXCLUDES deferred - those are next month's obligations)
	// pending = not yet billed transactions (current month + deferred from previous months)
	// outstanding = billed transactions to settle this month:
	//   1. deferred intent from previous months (billed)
	//   2. immediate intent from current month (billed)
	GetCCMetrics(ctx context.Context, arg GetCCMetricsParams) (GetCCMetricsRow, error)
	// Get total outstanding balance across all CC accounts (sum of unpaid expenses)
	GetCCOutstandingSummary(ctx context.Context, workspaceID int32) (GetCCOutstandingSummaryRow, error)
	// Returns all categories with their allocation for a specific month (0 if not set)
	GetCategoriesWithAllocations(ctx context.Context, arg GetCategoriesWithAllocationsParams) ([]GetCategoriesWithAllocationsRow, error)
	// Returns all transactions for a specific category in a month
	GetCategoryTransactions(ctx context.Context, arg GetCategoryTransactionsParams) ([]GetCategoryTransactionsRow, error)
	// Get completed loans (no remaining balance) with payment stats calculated from transactions
	GetCompletedLoansWithStats(ctx context.Context, workspaceID int32) ([]GetCompletedLoansWithStatsRow, error)
	GetConsolidatedProvidersByMonth(ctx context.Context, arg GetConsolidatedProvidersByMonthParams) ([]GetConsolidatedProvidersByMonthRow, error)
	GetCurrentPricesByItem(ctx context.Context, arg GetCurrentPricesByItemParams) ([]GetCurrentPricesByItemRow, error)
	// Get all billed, deferred transactions that need settlement (ordered by date)
	GetDeferredForSettlement(ctx context.Context, workspaceID int32) ([]GetDeferredForSettlementRow, error)
	// Get earliest unpaid month for a provider (for sequential enforcement)
	GetEarliestUnpaidLoanMonth(ctx context.Context, arg GetEarliestUnpaidLoanMonthParams) (GetEarliestUnpaidLoanMonthRow, error)
	GetExclusionsByTemplate(ctx context.Context, arg GetExclusionsByTemplateParams) ([]ProjectionExclusion, error)
	GetFirstItemImage(ctx context.Context, arg GetFirstItemImageParams) (pgtype.Text, error)
	GetGroupByID(ctx context.Context, arg GetGroupByIDParams) (GetGroupByIDRow, error)
	GetGroupsByMonth(ctx context.Context, arg GetGroupsByMonthParams) ([]GetGroupsByMonthRow, error)
	// Get billed transactions with immediate intent for the current month
	GetImmediateForSettlement(ctx context.Context, arg GetImmediateForSettlementParams) ([]GetImmediateForSettlementRow, error)
	GetLatestMonth(ctx context.Context, workspaceID int32) (Month, error)
	// Get latest paid month for a provider (for reverse sequential enforcement on unpay)
	GetLatestPaidLoanMonth(ctx context.Context, arg GetLatestPaidLoanMonthParams) (GetLatestPaidLoanMonthRow, error)
	GetLoanByID(ctx context.Context, arg GetLoanByIDParams) (Loan, error)
	// Convert loan transactions to LoanPayment format for frontend compatibility
	// Derives payment_number from row order, extracts year/month from transaction_date
	// Note: Only uses loan_id since service layer already verified loan ownership
	GetLoanPaymentsFromTransactions(ctx context.Context, loanID pgtype.Int4) ([]GetLoanPaymentsFromTransactionsRow, error)
	GetLoanProviderByID(ctx context.Context, arg GetLoanProviderByIDParams) (LoanProvider, error)
	// Get paid/unpaid transaction counts for delete confirmation
	GetLoanTransactionStats(ctx context.Context, arg GetLoanTransactionStatsParams) (GetLoanTransactionStatsRow, error)
	// ========================================
	// Loan Transaction Operations (CL v2)
	// ========================================
	// Get unpaid transactions for a specific loan and month
	GetLoanTransactionsByMonth(ctx context.Context, arg GetLoanTransactionsByMonthParams) ([]Transaction, error)
	// Aggregate loan transactions by month and provider for trend visualization
	// Returns monthly totals with provider breakdown
	GetLoanTrendData(ctx context.Context, arg GetLoanTrendDataParams) ([]GetLoanTrendDataRow, error)
	// CL v2: Use transactions with loan_id instead of loan_payments table
	// Get all loans with payment stats calculated from transactions
	GetLoansWithStats(ctx context.Context, workspaceID int32) ([]GetLoansWithStatsRow, error)
	// Get all loans for a specific provider with payment stats calculated from transactions
	// Orders unpaid items first, then by item name
	GetLoansWithStatsByProvider(ctx context.Context, arg GetLoansWithStatsByProviderParams) ([]GetLoansWithStatsByProviderRow, error)
	GetMonthByYearMonth(ctx context.Context, arg GetMonthByYearMonthParams) (Month, error)
	// Batch query to get income/expense totals grouped by year/month for N+1 prevention
	// Only count paid transactions, excludes transfers
	GetMonthlyTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetMonthlyTransactionSummariesRow, error)
	// Get CC transactions that are billed but overdue (2+ months old)
	GetOverdueCC(ctx context.Context, workspaceID int32) ([]GetOverdueCCRow, error)
	// Get paid loan payments for a specific provider and month (for unpay-month action)
	GetPaidLoanPaymentsByProviderMonth(ctx context.Context, arg GetPaidLoanPaymentsByProviderMonthParams) ([]GetPaidLoanPaymentsByProviderMonthRow, error)
	// Get pending CC transactions (billed_at IS NULL) for a specific month range
	GetPendingCCByMonth(ctx context.Context, arg GetPendingCCByMonthParams) ([]GetPendingCCByMonthRow, error)
	// Get pending (not yet billed) deferred CC transactions for visibility
	// These are transactions that will need to be paid next month once billed
	GetPendingDeferredCC(ctx context.Context, arg GetPendingDeferredCCParams) ([]GetPendingDeferredCCRow, error)
	// Get outstanding balance for each CC account
	GetPerAccountOutstanding(ctx context.Context, workspaceID int32) ([]GetPerAccountOutstandingRow, error)
	GetPriceHistoryByPlatform(ctx context.Context, arg GetPriceHistoryByPlatformParams) ([]WishlistItemPrice, error)
	// ========================================
	// Projection Management (v2)
	// ========================================
	// Get all projected transactions for a specific template
	GetProjectionsByTemplate(ctx context.Context, arg GetProjectionsByTemplateParams) ([]Transaction, error)
	// Returns recently used categories for suggestions dropdown
	GetRecentlyUsedCategories(ctx context.Context, workspaceID int32) ([]GetRecentlyUsedCategoriesRow, error)
	GetRecurringTemplateByID(ctx context.Context, arg GetRecurringTemplateByIDParams) (RecurringTemplate, error)
	// Returns total spending per category for a specific month
	GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	// Get multiple transactions by their IDs
	GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]Transaction, error)
	// Get all transactions for a specific loan (both paid and unpaid) for item-based modal
	GetTransactionsByLoanID(ctx context.Context, arg GetTransactionsByLoanIDParams) ([]Transaction, error)
	GetTransactionsByWorkspace(ctx context.Context, arg GetTransactionsByWorkspaceParams) ([]Transaction, error)
	// Returns all transactions in a date range with category name for aggregation (no pagination)
	// Used by dashboard future spending calculations
	GetTransactionsForAggregation(ctx context.Context, arg GetTransactionsForAggregationParams) ([]GetTransactionsForAggregationRow, error)
	// Returns transactions with category name and group name joined for display
	GetTransactionsWithCategory(ctx context.Context, arg GetTransactionsWithCategoryParams) ([]GetTransactionsWithCategoryRow, error)
	GetUngroupedTransactionIDsByProviderMonth(ctx context.Context, arg GetUngroupedTransactionIDsByProviderMonthParams) ([]int32, error)
	GetUngroupedTransactionsByMonth(ctx context.Context, arg GetUngroupedTransactionsByMonthParams) ([]Transaction, error)
	// Get unpaid loan payments for a specific provider and month (for pay-month action)
	GetUnpaidLoanPaymentsByProviderMonth(ctx context.Context, arg GetUnpaidLoanPaymentsByProviderMonthParams) ([]GetUnpaidLoanPaymentsByProviderMonthRow, error)
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWishlistByID(ctx context.Context, arg GetWishlistByIDParams) (Wishlist, error)
	GetWishlistByName(ctx context.Context, arg GetWishlistByNameParams) (Wishlist, error)
	GetWishlistItemByID(ctx context.Context, arg GetWishlistItemByIDParams) (WishlistItem, error)
	GetWishlistItemNoteByID(ctx context.Context, arg GetWishlistItemNoteByIDParams) (WishlistItemNote, error)
	GetWishlistItemPriceByID(ctx context.Context, arg GetWishlistItemPriceByIDParams) (WishlistItemPrice, error)
	GetWorkspaceByID(ctx context.Context, id int32) (Workspace, error)
	GetWorkspaceByUserAuth0ID(ctx context.Context, auth0ID string) (Workspace, error)
	GetWorkspaceByUserID(ctx context.Context, userID pgtype.UUID) (Workspace, error)
	HardDeleteAccount(ctx context.Context, arg HardDeleteAccountParams) error
	// Check if any transactions for this loan are paid (for provider change validation)
	HasPaidTransactionsByLoan(ctx context.Context, arg HasPaidTransactionsByLoanParams) (bool, error)
	IsMonthExcluded(ctx context.Context, arg IsMonthExcludedParams) (bool, error)
	ListActiveLoans(ctx context.Context, arg ListActiveLoansParams) ([]Loan, error)
	ListCompletedLoans(ctx context.Context, arg ListCompletedLoansParams) ([]Loan, error)
	ListLoanProviders(ctx context.Context, workspaceID int32) ([]LoanProvider, error)
	ListLoans(ctx context.Context, workspaceID int32) ([]Loan, error)
	ListNotesByItemAsc(ctx context.Context, arg ListNotesByItemAscParams) ([]WishlistItemNote, error)
	ListNotesByItemDesc(ctx context.Context, arg ListNotesByItemDescParams) ([]WishlistItemNote, error)
	ListPricesByItem(ctx context.Context, arg ListPricesByItemParams) ([]WishlistItemPrice, error)
	ListRecurringTemplatesByWorkspace(ctx context.Context, workspaceID int32) ([]RecurringTemplate, error)
	ListWishlistItems(ctx context.Context, arg ListWishlistItemsParams) ([]WishlistItem, error)
	ListWishlistItemsWithStats(ctx context.Context, arg ListWishlistItemsWithStatsParams) ([]ListWishlistItemsWithStatsRow, error)
	ListWishlists(ctx context.Context, workspaceID int32) ([]Wishlist, error)
	MoveWishlistItem(ctx context.Context, arg MoveWishlistItemParams) (WishlistItem, error)
	// Unlink actual transactions from template (keep them, clear template_id)
	OrphanActualsByTemplate(ctx context.Context, arg OrphanActualsByTemplateParams) error
	// Unlink paid transactions from loan (keep them, clear loan_id)
	// Used when deleting a loan to preserve payment history
	OrphanPaidTransactionsByLoan(ctx context.Context, arg OrphanPaidTransactionsByLoanParams) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error)
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (int64, error)
	SoftDeleteBudgetCategory(ctx context.Context, arg SoftDeleteBudgetCategoryParams) error
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error)
	SoftDeleteTransactionsByGroupID(ctx context.Context, arg SoftDeleteTransactionsByGroupIDParams) (int64, error)
	SoftDeleteTransferPair(ctx context.Context, arg SoftDeleteTransferPairParams) (int64, error)
	// Sum deferred CC expenses within a date range
	// Used for next month projections
	SumDeferredCCByDateRange(ctx context.Context, arg SumDeferredCCByDateRangeParams) (pgtype.Numeric, error)
	// Sum paid expenses within a date range for in-hand balance calculation
	// Excludes transfers (they move money between accounts, not actual spending)
	SumPaidExpensesByDateRange(ctx context.Context, arg SumPaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	// Only count paid transactions, excludes transfers
	SumTransactionsByTypeAndDateRange(ctx context.Context, arg SumTransactionsByTypeAndDateRangeParams) (pgtype.Numeric, error)
	// Sum unpaid expenses within a date range (ALL unpaid, including deferred CC)
	// Used for balance calculations where all obligations matter
	// Excludes transfers (they move money between accounts, not actual spending)
	SumUnpaidExpensesByDateRange(ctx context.Context, arg SumUnpaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	// Sum unpaid expenses for disposable income calculation
	// EXCLUDES deferred CC transactions (those are for next month)
	// EXCLUDES transfers (they move money between accounts, not actual spending)
	// Includes: non-CC unpaid expenses + immediate CC expenses
	SumUnpaidExpensesForDisposable(ctx context.Context, arg SumUnpaidExpensesForDisposableParams) (pgtype.Numeric, error)
	// ========================================
	// CC Lifecycle Operations (v2 - Simplified)
	// CC State: pending (billed_at IS NULL), billed (billed_at IS NOT NULL, is_paid=false), settled (is_paid=true)
	// ========================================
	// Toggle billed status for a CC transaction (pending <-> billed)
	ToggleBilledStatus(ctx context.Context, arg ToggleBilledStatusParams) (Transaction, error)
	ToggleTransactionPaidStatus(ctx context.Context, arg ToggleTransactionPaidStatusParams) (Transaction, error)
	UnassignAllFromGroup(ctx context.Context, arg UnassignAllFromGroupParams) (int64, error)
	UnassignGroupFromTransactions(ctx context.Context, arg UnassignGroupFromTransactionsParams) error
	UpdateAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudgetCategory(ctx context.Context, arg UpdateBudgetCategoryParams) (BudgetCategory, error)
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (TransactionGroup, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	// Updates editable fields with optional provider change
	// Provider can only change if no payments have been made (validated at service layer)
	UpdateLoanEditableFields(ctx context.Context, arg UpdateLoanEditableFieldsParams) (Loan, error)
	// Only updates editable fields (item_name, notes) - amount/months/dates are locked after creation
	UpdateLoanPartial(ctx context.Context, arg UpdateLoanPartialParams) (Loan, error)
	UpdateLoanProvider(ctx context.Context, arg UpdateLoanProviderParams) (LoanProvider, error)
	UpdateMonthStartingBalance(ctx context.Context, arg UpdateMonthStartingBalanceParams) error
	UpdateRecurringTemplate(ctx context.Context, arg UpdateRecurringTemplateParams) (RecurringTemplate, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	// Cascade item name/provider change to transaction payees
	// Pattern: "[Provider] ([Item Name])"
	UpdateTransactionPayeesByLoan(ctx context.Context, arg UpdateTransactionPayeesByLoanParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateWishlist(ctx context.Context, arg UpdateWishlistParams) (Wishlist, error)
	UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WishlistItem, error)
	UpdateWishlistItemNote(ctx context.Context, arg UpdateWishlistItemNoteParams) (WishlistItemNote, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertBudgetAllocation(ctx context.Context, arg UpsertBudgetAllocationParams) (BudgetAllocation, error)
}

var _ Querier = (*Queries)(nil)
