// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Batch toggle multiple transactions from pending to billed
	BatchToggleToBilled(ctx context.Context, arg BatchToggleToBilledParams) ([]Transaction, error)
	// Bulk update multiple transactions to settled state (is_paid = true)
	BulkSettleTransactions(ctx context.Context, arg BulkSettleTransactionsParams) ([]Transaction, error)
	// Copies all allocations from one month to another (atomic, skips deleted categories)
	CopyAllocationsToMonth(ctx context.Context, arg CopyAllocationsToMonthParams) error
	CountActiveLoansByProvider(ctx context.Context, arg CountActiveLoansByProviderParams) (int64, error)
	// Returns the count of allocations for a specific month (for lazy initialization check)
	CountAllocationsForMonth(ctx context.Context, arg CountAllocationsForMonthParams) (int64, error)
	CountNotesByItem(ctx context.Context, arg CountNotesByItemParams) (int64, error)
	// Count transactions assigned to a specific category
	CountTransactionsByCategory(ctx context.Context, arg CountTransactionsByCategoryParams) (int64, error)
	CountTransactionsByWorkspace(ctx context.Context, arg CountTransactionsByWorkspaceParams) (int64, error)
	CountWishlistItems(ctx context.Context, arg CountWishlistItemsParams) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudgetCategory(ctx context.Context, arg CreateBudgetCategoryParams) (BudgetCategory, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLoanPayment(ctx context.Context, arg CreateLoanPaymentParams) (LoanPayment, error)
	CreateLoanProvider(ctx context.Context, arg CreateLoanProviderParams) (LoanProvider, error)
	CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error)
	CreateOrGetUserByAuth0ID(ctx context.Context, arg CreateOrGetUserByAuth0IDParams) (User, error)
	CreateProjectionExclusion(ctx context.Context, arg CreateProjectionExclusionParams) error
	// Recurring Templates (recurring_templates table)
	CreateRecurringTemplate(ctx context.Context, arg CreateRecurringTemplateParams) (RecurringTemplate, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWishlist(ctx context.Context, arg CreateWishlistParams) (Wishlist, error)
	CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error)
	CreateWishlistItemNote(ctx context.Context, arg CreateWishlistItemNoteParams) (WishlistItemNote, error)
	CreateWishlistItemPrice(ctx context.Context, arg CreateWishlistItemPriceParams) (WishlistItemPrice, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteBudgetAllocation(ctx context.Context, arg DeleteBudgetAllocationParams) error
	DeleteExclusionsByTemplate(ctx context.Context, templateID int32) error
	DeleteLoan(ctx context.Context, arg DeleteLoanParams) error
	DeleteLoanProvider(ctx context.Context, arg DeleteLoanProviderParams) error
	// Delete projections beyond a specific date (used when changing template end_date)
	DeleteProjectionsBeyondDate(ctx context.Context, arg DeleteProjectionsBeyondDateParams) error
	// Delete all projected transactions for a template (used when deleting template)
	DeleteProjectionsByTemplate(ctx context.Context, arg DeleteProjectionsByTemplateParams) error
	DeleteRecurringTemplate(ctx context.Context, arg DeleteRecurringTemplateParams) error
	DeleteWishlist(ctx context.Context, arg DeleteWishlistParams) error
	DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error
	DeleteWishlistItemNote(ctx context.Context, arg DeleteWishlistItemNoteParams) error
	DeleteWishlistItemPrice(ctx context.Context, arg DeleteWishlistItemPriceParams) error
	DeleteWorkspace(ctx context.Context, id int32) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, arg GetAPITokenByIDParams) (ApiToken, error)
	GetAPITokensByWorkspace(ctx context.Context, workspaceID int32) ([]ApiToken, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAccountByIDIncludeDeleted(ctx context.Context, arg GetAccountByIDIncludeDeletedParams) (Account, error)
	// Only count paid transactions for balance calculations
	GetAccountTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetAccountTransactionSummariesRow, error)
	GetAccountsByWorkspace(ctx context.Context, workspaceID int32) ([]Account, error)
	GetAccountsByWorkspaceAll(ctx context.Context, workspaceID int32) ([]Account, error)
	GetActiveLoansWithStats(ctx context.Context, workspaceID int32) ([]GetActiveLoansWithStatsRow, error)
	GetActiveRecurringTemplates(ctx context.Context, workspaceID int32) ([]RecurringTemplate, error)
	// Get all active templates across all workspaces (for daily sync goroutine)
	GetAllActiveTemplates(ctx context.Context) ([]RecurringTemplate, error)
	GetAllBudgetCategories(ctx context.Context, workspaceID int32) ([]BudgetCategory, error)
	GetAllMonths(ctx context.Context, workspaceID int32) ([]Month, error)
	GetBestPriceForItem(ctx context.Context, arg GetBestPriceForItemParams) (string, error)
	// Get billed CC transactions with deferred settlement intent for a month range
	GetBilledCCByMonth(ctx context.Context, arg GetBilledCCByMonthParams) ([]GetBilledCCByMonthRow, error)
	GetBudgetAllocationByCategory(ctx context.Context, arg GetBudgetAllocationByCategoryParams) (BudgetAllocation, error)
	GetBudgetAllocationsByMonth(ctx context.Context, arg GetBudgetAllocationsByMonthParams) ([]GetBudgetAllocationsByMonthRow, error)
	GetBudgetCategoryByID(ctx context.Context, arg GetBudgetCategoryByIDParams) (BudgetCategory, error)
	GetBudgetCategoryByName(ctx context.Context, arg GetBudgetCategoryByNameParams) (BudgetCategory, error)
	// Get CC metrics (pending, outstanding, purchases) for a month range
	// Simplified: pending = billed_at IS NULL, billed = billed_at IS NOT NULL AND is_paid = false, settled = is_paid = true
	// purchases = CC expenses this month (only expenses, income is payments against balance)
	// outstanding = billed transactions to settle this month:
	//   1. deferred intent from previous months
	//   2. immediate intent from current month
	GetCCMetrics(ctx context.Context, arg GetCCMetricsParams) (GetCCMetricsRow, error)
	// Get total outstanding balance across all CC accounts (sum of unpaid expenses)
	GetCCOutstandingSummary(ctx context.Context, workspaceID int32) (GetCCOutstandingSummaryRow, error)
	// Returns all categories with their allocation for a specific month (0 if not set)
	GetCategoriesWithAllocations(ctx context.Context, arg GetCategoriesWithAllocationsParams) ([]GetCategoriesWithAllocationsRow, error)
	// Returns all transactions for a specific category in a month
	GetCategoryTransactions(ctx context.Context, arg GetCategoryTransactionsParams) ([]GetCategoryTransactionsRow, error)
	GetCompletedLoansWithStats(ctx context.Context, workspaceID int32) ([]GetCompletedLoansWithStatsRow, error)
	GetCurrentPricesByItem(ctx context.Context, arg GetCurrentPricesByItemParams) ([]GetCurrentPricesByItemRow, error)
	// Get all billed, deferred transactions that need settlement (ordered by date)
	GetDeferredForSettlement(ctx context.Context, workspaceID int32) ([]GetDeferredForSettlementRow, error)
	GetExclusionsByTemplate(ctx context.Context, arg GetExclusionsByTemplateParams) ([]ProjectionExclusion, error)
	GetFirstItemImage(ctx context.Context, arg GetFirstItemImageParams) (pgtype.Text, error)
	// Get billed transactions with immediate intent for the current month
	GetImmediateForSettlement(ctx context.Context, arg GetImmediateForSettlementParams) ([]GetImmediateForSettlementRow, error)
	GetLatestMonth(ctx context.Context, workspaceID int32) (Month, error)
	GetLoanByID(ctx context.Context, arg GetLoanByIDParams) (Loan, error)
	GetLoanDeleteStats(ctx context.Context, loanID int32) (GetLoanDeleteStatsRow, error)
	GetLoanPaymentByID(ctx context.Context, id int32) (LoanPayment, error)
	GetLoanPaymentByLoanAndNumber(ctx context.Context, arg GetLoanPaymentByLoanAndNumberParams) (LoanPayment, error)
	GetLoanPaymentsByLoanID(ctx context.Context, loanID int32) ([]LoanPayment, error)
	GetLoanPaymentsByMonth(ctx context.Context, arg GetLoanPaymentsByMonthParams) ([]LoanPayment, error)
	GetLoanPaymentsWithDetailsByMonth(ctx context.Context, arg GetLoanPaymentsWithDetailsByMonthParams) ([]GetLoanPaymentsWithDetailsByMonthRow, error)
	GetLoanProviderByID(ctx context.Context, arg GetLoanProviderByIDParams) (LoanProvider, error)
	GetLoansWithStats(ctx context.Context, workspaceID int32) ([]GetLoansWithStatsRow, error)
	GetMonthByYearMonth(ctx context.Context, arg GetMonthByYearMonthParams) (Month, error)
	// Batch query to get income/expense totals grouped by year/month for N+1 prevention
	// Only count paid transactions
	GetMonthlyTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetMonthlyTransactionSummariesRow, error)
	// Get CC transactions that are billed but overdue (2+ months old)
	GetOverdueCC(ctx context.Context, workspaceID int32) ([]GetOverdueCCRow, error)
	// Get pending CC transactions (billed_at IS NULL) for a specific month range
	GetPendingCCByMonth(ctx context.Context, arg GetPendingCCByMonthParams) ([]GetPendingCCByMonthRow, error)
	// Get outstanding balance for each CC account
	GetPerAccountOutstanding(ctx context.Context, workspaceID int32) ([]GetPerAccountOutstandingRow, error)
	GetPriceHistoryByPlatform(ctx context.Context, arg GetPriceHistoryByPlatformParams) ([]WishlistItemPrice, error)
	// ========================================
	// Projection Management (v2)
	// ========================================
	// Get all projected transactions for a specific template
	GetProjectionsByTemplate(ctx context.Context, arg GetProjectionsByTemplateParams) ([]Transaction, error)
	// Returns recently used categories for suggestions dropdown
	GetRecentlyUsedCategories(ctx context.Context, workspaceID int32) ([]GetRecentlyUsedCategoriesRow, error)
	GetRecurringTemplateByID(ctx context.Context, arg GetRecurringTemplateByIDParams) (RecurringTemplate, error)
	// Returns total spending per category for a specific month
	GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	// Get multiple transactions by their IDs
	GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]Transaction, error)
	GetTransactionsByWorkspace(ctx context.Context, arg GetTransactionsByWorkspaceParams) ([]Transaction, error)
	// Returns all transactions in a date range with category name for aggregation (no pagination)
	// Used by dashboard future spending calculations
	GetTransactionsForAggregation(ctx context.Context, arg GetTransactionsForAggregationParams) ([]GetTransactionsForAggregationRow, error)
	// Returns transactions with category name joined for display
	GetTransactionsWithCategory(ctx context.Context, arg GetTransactionsWithCategoryParams) ([]GetTransactionsWithCategoryRow, error)
	GetUnpaidLoanPaymentsByMonth(ctx context.Context, arg GetUnpaidLoanPaymentsByMonthParams) ([]LoanPayment, error)
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWishlistByID(ctx context.Context, arg GetWishlistByIDParams) (Wishlist, error)
	GetWishlistByName(ctx context.Context, arg GetWishlistByNameParams) (Wishlist, error)
	GetWishlistItemByID(ctx context.Context, arg GetWishlistItemByIDParams) (WishlistItem, error)
	GetWishlistItemNoteByID(ctx context.Context, arg GetWishlistItemNoteByIDParams) (WishlistItemNote, error)
	GetWishlistItemPriceByID(ctx context.Context, arg GetWishlistItemPriceByIDParams) (WishlistItemPrice, error)
	GetWorkspaceByID(ctx context.Context, id int32) (Workspace, error)
	GetWorkspaceByUserAuth0ID(ctx context.Context, auth0ID string) (Workspace, error)
	GetWorkspaceByUserID(ctx context.Context, userID pgtype.UUID) (Workspace, error)
	HardDeleteAccount(ctx context.Context, arg HardDeleteAccountParams) error
	IsMonthExcluded(ctx context.Context, arg IsMonthExcludedParams) (bool, error)
	ListActiveLoans(ctx context.Context, arg ListActiveLoansParams) ([]Loan, error)
	ListCompletedLoans(ctx context.Context, arg ListCompletedLoansParams) ([]Loan, error)
	ListLoanProviders(ctx context.Context, workspaceID int32) ([]LoanProvider, error)
	ListLoans(ctx context.Context, workspaceID int32) ([]Loan, error)
	ListNotesByItemAsc(ctx context.Context, arg ListNotesByItemAscParams) ([]WishlistItemNote, error)
	ListNotesByItemDesc(ctx context.Context, arg ListNotesByItemDescParams) ([]WishlistItemNote, error)
	ListPricesByItem(ctx context.Context, arg ListPricesByItemParams) ([]WishlistItemPrice, error)
	ListRecurringTemplatesByWorkspace(ctx context.Context, workspaceID int32) ([]RecurringTemplate, error)
	ListWishlistItems(ctx context.Context, arg ListWishlistItemsParams) ([]WishlistItem, error)
	ListWishlistItemsWithStats(ctx context.Context, arg ListWishlistItemsWithStatsParams) ([]ListWishlistItemsWithStatsRow, error)
	ListWishlists(ctx context.Context, workspaceID int32) ([]Wishlist, error)
	MoveWishlistItem(ctx context.Context, arg MoveWishlistItemParams) (WishlistItem, error)
	// Unlink actual transactions from template (keep them, clear template_id)
	OrphanActualsByTemplate(ctx context.Context, arg OrphanActualsByTemplateParams) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error)
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) (int64, error)
	SoftDeleteBudgetCategory(ctx context.Context, arg SoftDeleteBudgetCategoryParams) error
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error)
	SoftDeleteTransferPair(ctx context.Context, arg SoftDeleteTransferPairParams) (int64, error)
	// Sum paid expenses within a date range for in-hand balance calculation
	SumPaidExpensesByDateRange(ctx context.Context, arg SumPaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	// Only count paid transactions
	SumTransactionsByTypeAndDateRange(ctx context.Context, arg SumTransactionsByTypeAndDateRangeParams) (pgtype.Numeric, error)
	// Sum unpaid expenses within a date range for disposable income calculation
	SumUnpaidExpensesByDateRange(ctx context.Context, arg SumUnpaidExpensesByDateRangeParams) (pgtype.Numeric, error)
	SumUnpaidLoanPaymentsByMonth(ctx context.Context, arg SumUnpaidLoanPaymentsByMonthParams) (pgtype.Numeric, error)
	// ========================================
	// CC Lifecycle Operations (v2 - Simplified)
	// CC State: pending (billed_at IS NULL), billed (billed_at IS NOT NULL, is_paid=false), settled (is_paid=true)
	// ========================================
	// Toggle billed status for a CC transaction (pending <-> billed)
	ToggleBilledStatus(ctx context.Context, arg ToggleBilledStatusParams) (Transaction, error)
	ToggleLoanPaymentPaid(ctx context.Context, arg ToggleLoanPaymentPaidParams) (LoanPayment, error)
	ToggleTransactionPaidStatus(ctx context.Context, arg ToggleTransactionPaidStatusParams) (Transaction, error)
	UpdateAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudgetCategory(ctx context.Context, arg UpdateBudgetCategoryParams) (BudgetCategory, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	// Only updates editable fields (item_name, notes) - amount/months/dates are locked after creation
	UpdateLoanPartial(ctx context.Context, arg UpdateLoanPartialParams) (Loan, error)
	UpdateLoanPaymentAmount(ctx context.Context, arg UpdateLoanPaymentAmountParams) (LoanPayment, error)
	UpdateLoanProvider(ctx context.Context, arg UpdateLoanProviderParams) (LoanProvider, error)
	UpdateMonthStartingBalance(ctx context.Context, arg UpdateMonthStartingBalanceParams) error
	UpdateRecurringTemplate(ctx context.Context, arg UpdateRecurringTemplateParams) (RecurringTemplate, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateWishlist(ctx context.Context, arg UpdateWishlistParams) (Wishlist, error)
	UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WishlistItem, error)
	UpdateWishlistItemNote(ctx context.Context, arg UpdateWishlistItemNoteParams) (WishlistItemNote, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertBudgetAllocation(ctx context.Context, arg UpsertBudgetAllocationParams) (BudgetAllocation, error)
}

var _ Querier = (*Queries)(nil)
