// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchToggleToBilled = `-- name: BatchToggleToBilled :many
UPDATE transactions
SET billed_at = NOW(),
    updated_at = NOW()
WHERE id = ANY($1::int[])
  AND workspace_id = $2
  AND billed_at IS NULL
  AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type BatchToggleToBilledParams struct {
	Column1     []int32 `json:"column_1"`
	WorkspaceID int32   `json:"workspace_id"`
}

// Batch toggle multiple transactions from pending to billed
func (q *Queries) BatchToggleToBilled(ctx context.Context, arg BatchToggleToBilledParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, batchToggleToBilled, arg.Column1, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkSettleTransactions = `-- name: BulkSettleTransactions :many
UPDATE transactions
SET is_paid = true,
    updated_at = NOW()
WHERE id = ANY($1::int[])
  AND workspace_id = $2
  AND billed_at IS NOT NULL
  AND is_paid = false
  AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type BulkSettleTransactionsParams struct {
	Column1     []int32 `json:"column_1"`
	WorkspaceID int32   `json:"workspace_id"`
}

// Bulk update multiple transactions to settled state (is_paid = true)
func (q *Queries) BulkSettleTransactions(ctx context.Context, arg BulkSettleTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, bulkSettleTransactions, arg.Column1, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactionsByWorkspace = `-- name: CountTransactionsByWorkspace :one
SELECT COUNT(*) FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR account_id = $2)
  AND ($3::DATE IS NULL OR transaction_date >= $3)
  AND ($4::DATE IS NULL OR transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR type = $5)
`

type CountTransactionsByWorkspaceParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	AccountID   pgtype.Int4 `json:"account_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Type        pgtype.Text `json:"type"`
}

func (q *Queries) CountTransactionsByWorkspace(ctx context.Context, arg CountTransactionsByWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByWorkspace,
		arg.WorkspaceID,
		arg.AccountID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    workspace_id, account_id, name, amount, type,
    transaction_date, is_paid, notes, transfer_pair_id, category_id, is_cc_payment,
    billed_at, settlement_intent,
    source, template_id, is_projected
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type CreateTransactionParams struct {
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.IsPaid,
		arg.Notes,
		arg.TransferPairID,
		arg.CategoryID,
		arg.IsCcPayment,
		arg.BilledAt,
		arg.SettlementIntent,
		arg.Source,
		arg.TemplateID,
		arg.IsProjected,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.BilledAt,
		&i.SettlementIntent,
		&i.Source,
		&i.TemplateID,
		&i.IsProjected,
	)
	return i, err
}

const deleteProjectionsBeyondDate = `-- name: DeleteProjectionsBeyondDate :exec
DELETE FROM transactions
WHERE workspace_id = $1
  AND template_id = $2
  AND is_projected = true
  AND transaction_date > $3
`

type DeleteProjectionsBeyondDateParams struct {
	WorkspaceID     int32       `json:"workspace_id"`
	TemplateID      pgtype.Int4 `json:"template_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

// Delete projections beyond a specific date (used when changing template end_date)
func (q *Queries) DeleteProjectionsBeyondDate(ctx context.Context, arg DeleteProjectionsBeyondDateParams) error {
	_, err := q.db.Exec(ctx, deleteProjectionsBeyondDate, arg.WorkspaceID, arg.TemplateID, arg.TransactionDate)
	return err
}

const deleteProjectionsByTemplate = `-- name: DeleteProjectionsByTemplate :exec
DELETE FROM transactions
WHERE workspace_id = $1
  AND template_id = $2
  AND is_projected = true
`

type DeleteProjectionsByTemplateParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	TemplateID  pgtype.Int4 `json:"template_id"`
}

// Delete all projected transactions for a template (used when deleting template)
func (q *Queries) DeleteProjectionsByTemplate(ctx context.Context, arg DeleteProjectionsByTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteProjectionsByTemplate, arg.WorkspaceID, arg.TemplateID)
	return err
}

const getAccountTransactionSummaries = `-- name: GetAccountTransactionSummaries :many
SELECT
    account_id,
    COALESCE(SUM(CASE WHEN type = 'income' AND is_paid = true THEN amount ELSE 0 END), 0) AS sum_income,
    COALESCE(SUM(CASE WHEN type = 'expense' AND is_paid = true THEN amount ELSE 0 END), 0) AS sum_expenses,
    COALESCE(SUM(CASE WHEN type = 'expense' AND is_paid = false THEN amount ELSE 0 END), 0) AS sum_unpaid_expenses,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0) AS sum_all_expenses
FROM transactions
WHERE workspace_id = $1 AND deleted_at IS NULL
GROUP BY account_id
`

type GetAccountTransactionSummariesRow struct {
	AccountID         int32       `json:"account_id"`
	SumIncome         interface{} `json:"sum_income"`
	SumExpenses       interface{} `json:"sum_expenses"`
	SumUnpaidExpenses interface{} `json:"sum_unpaid_expenses"`
	SumAllExpenses    interface{} `json:"sum_all_expenses"`
}

// For regular accounts: only count paid transactions
// For CC accounts: count all expenses (isPaid means settled, not whether purchase happened)
func (q *Queries) GetAccountTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetAccountTransactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, getAccountTransactionSummaries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountTransactionSummariesRow{}
	for rows.Next() {
		var i GetAccountTransactionSummariesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.SumIncome,
			&i.SumExpenses,
			&i.SumUnpaidExpenses,
			&i.SumAllExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBilledCCByMonth = `-- name: GetBilledCCByMonth :many
SELECT t.id, t.workspace_id, account_id, t.name, amount, type, transaction_date, is_paid, notes, t.created_at, t.updated_at, t.deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected, a.id, a.workspace_id, a.name, account_type, template, initial_balance, a.created_at, a.updated_at, a.deleted_at FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND t.billed_at IS NOT NULL
  AND t.is_paid = false
  AND t.settlement_intent = 'deferred'
  AND t.transaction_date >= $2 AND t.transaction_date < $3
  AND t.deleted_at IS NULL
ORDER BY t.transaction_date DESC
`

type GetBilledCCByMonthParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetBilledCCByMonthRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	ID_2             int32              `json:"id_2"`
	WorkspaceID_2    int32              `json:"workspace_id_2"`
	Name_2           string             `json:"name_2"`
	AccountType      string             `json:"account_type"`
	Template         string             `json:"template"`
	InitialBalance   pgtype.Numeric     `json:"initial_balance"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2      pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2      pgtype.Timestamptz `json:"deleted_at_2"`
}

// Get billed CC transactions with deferred settlement intent for a month range
func (q *Queries) GetBilledCCByMonth(ctx context.Context, arg GetBilledCCByMonthParams) ([]GetBilledCCByMonthRow, error) {
	rows, err := q.db.Query(ctx, getBilledCCByMonth, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBilledCCByMonthRow{}
	for rows.Next() {
		var i GetBilledCCByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.ID_2,
			&i.WorkspaceID_2,
			&i.Name_2,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCCMetrics = `-- name: GetCCMetrics :one
SELECT
    COALESCE(SUM(CASE WHEN t.billed_at IS NULL AND t.is_paid = false AND t.transaction_date >= $2 AND t.transaction_date < $3 THEN t.amount ELSE 0 END), 0)::NUMERIC(12,2) as pending_total,
    COALESCE(SUM(CASE WHEN t.billed_at IS NOT NULL AND t.is_paid = false AND (
        (t.settlement_intent = 'deferred' AND t.transaction_date < $2) OR
        (t.settlement_intent = 'immediate' AND t.transaction_date >= $2 AND t.transaction_date < $3)
    ) THEN t.amount ELSE 0 END), 0)::NUMERIC(12,2) as outstanding_total,
    COALESCE(SUM(CASE WHEN t.type = 'expense' AND t.transaction_date >= $2 AND t.transaction_date < $3 THEN t.amount ELSE 0 END), 0)::NUMERIC(12,2) as purchases_total
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND (
    (t.transaction_date >= $2 AND t.transaction_date < $3) OR
    (t.billed_at IS NOT NULL AND t.is_paid = false AND t.settlement_intent = 'deferred' AND t.transaction_date < $2)
  )
  AND t.deleted_at IS NULL
`

type GetCCMetricsParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetCCMetricsRow struct {
	PendingTotal     pgtype.Numeric `json:"pending_total"`
	OutstandingTotal pgtype.Numeric `json:"outstanding_total"`
	PurchasesTotal   pgtype.Numeric `json:"purchases_total"`
}

// Get CC metrics (pending, outstanding, purchases) for a month range
// Simplified: pending = billed_at IS NULL, billed = billed_at IS NOT NULL AND is_paid = false, settled = is_paid = true
// purchases = CC expenses this month (only expenses, income is payments against balance)
// outstanding = billed transactions to settle this month:
//  1. deferred intent from previous months
//  2. immediate intent from current month
func (q *Queries) GetCCMetrics(ctx context.Context, arg GetCCMetricsParams) (GetCCMetricsRow, error) {
	row := q.db.QueryRow(ctx, getCCMetrics, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var i GetCCMetricsRow
	err := row.Scan(&i.PendingTotal, &i.OutstandingTotal, &i.PurchasesTotal)
	return i, err
}

const getDeferredForSettlement = `-- name: GetDeferredForSettlement :many
SELECT t.id, t.workspace_id, account_id, t.name, amount, type, transaction_date, is_paid, notes, t.created_at, t.updated_at, t.deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected, a.id, a.workspace_id, a.name, account_type, template, initial_balance, a.created_at, a.updated_at, a.deleted_at FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND t.billed_at IS NOT NULL
  AND t.is_paid = false
  AND t.settlement_intent = 'deferred'
  AND t.deleted_at IS NULL
ORDER BY t.transaction_date ASC
`

type GetDeferredForSettlementRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	ID_2             int32              `json:"id_2"`
	WorkspaceID_2    int32              `json:"workspace_id_2"`
	Name_2           string             `json:"name_2"`
	AccountType      string             `json:"account_type"`
	Template         string             `json:"template"`
	InitialBalance   pgtype.Numeric     `json:"initial_balance"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2      pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2      pgtype.Timestamptz `json:"deleted_at_2"`
}

// Get all billed, deferred transactions that need settlement (ordered by date)
func (q *Queries) GetDeferredForSettlement(ctx context.Context, workspaceID int32) ([]GetDeferredForSettlementRow, error) {
	rows, err := q.db.Query(ctx, getDeferredForSettlement, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeferredForSettlementRow{}
	for rows.Next() {
		var i GetDeferredForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.ID_2,
			&i.WorkspaceID_2,
			&i.Name_2,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImmediateForSettlement = `-- name: GetImmediateForSettlement :many
SELECT t.id, t.workspace_id, account_id, t.name, amount, type, transaction_date, is_paid, notes, t.created_at, t.updated_at, t.deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected, a.id, a.workspace_id, a.name, account_type, template, initial_balance, a.created_at, a.updated_at, a.deleted_at FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND t.billed_at IS NOT NULL
  AND t.is_paid = false
  AND t.settlement_intent = 'immediate'
  AND t.transaction_date >= $2
  AND t.transaction_date < $3
  AND t.deleted_at IS NULL
ORDER BY t.transaction_date ASC
`

type GetImmediateForSettlementParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetImmediateForSettlementRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	ID_2             int32              `json:"id_2"`
	WorkspaceID_2    int32              `json:"workspace_id_2"`
	Name_2           string             `json:"name_2"`
	AccountType      string             `json:"account_type"`
	Template         string             `json:"template"`
	InitialBalance   pgtype.Numeric     `json:"initial_balance"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2      pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2      pgtype.Timestamptz `json:"deleted_at_2"`
}

// Get billed transactions with immediate intent for the current month
func (q *Queries) GetImmediateForSettlement(ctx context.Context, arg GetImmediateForSettlementParams) ([]GetImmediateForSettlementRow, error) {
	rows, err := q.db.Query(ctx, getImmediateForSettlement, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImmediateForSettlementRow{}
	for rows.Next() {
		var i GetImmediateForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.ID_2,
			&i.WorkspaceID_2,
			&i.Name_2,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTransactionSummaries = `-- name: GetMonthlyTransactionSummaries :many
SELECT
    EXTRACT(YEAR FROM transaction_date)::INTEGER AS year,
    EXTRACT(MONTH FROM transaction_date)::INTEGER AS month,
    COALESCE(SUM(CASE WHEN type = 'income' AND is_paid = true THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' AND is_paid = true THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS total_expenses
FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
GROUP BY EXTRACT(YEAR FROM transaction_date), EXTRACT(MONTH FROM transaction_date)
ORDER BY year DESC, month DESC
`

type GetMonthlyTransactionSummariesRow struct {
	Year          int32          `json:"year"`
	Month         int32          `json:"month"`
	TotalIncome   pgtype.Numeric `json:"total_income"`
	TotalExpenses pgtype.Numeric `json:"total_expenses"`
}

// Batch query to get income/expense totals grouped by year/month for N+1 prevention
// Only count paid transactions
func (q *Queries) GetMonthlyTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetMonthlyTransactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTransactionSummaries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTransactionSummariesRow{}
	for rows.Next() {
		var i GetMonthlyTransactionSummariesRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.TotalIncome,
			&i.TotalExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdueCC = `-- name: GetOverdueCC :many
SELECT t.id, t.workspace_id, account_id, t.name, amount, type, transaction_date, is_paid, notes, t.created_at, t.updated_at, t.deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected, a.id, a.workspace_id, a.name, account_type, template, initial_balance, a.created_at, a.updated_at, a.deleted_at FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND t.billed_at IS NOT NULL
  AND t.is_paid = false
  AND t.settlement_intent = 'deferred'
  AND t.billed_at < NOW() - INTERVAL '2 months'
  AND t.deleted_at IS NULL
ORDER BY t.billed_at ASC
`

type GetOverdueCCRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	ID_2             int32              `json:"id_2"`
	WorkspaceID_2    int32              `json:"workspace_id_2"`
	Name_2           string             `json:"name_2"`
	AccountType      string             `json:"account_type"`
	Template         string             `json:"template"`
	InitialBalance   pgtype.Numeric     `json:"initial_balance"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2      pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2      pgtype.Timestamptz `json:"deleted_at_2"`
}

// Get CC transactions that are billed but overdue (2+ months old)
func (q *Queries) GetOverdueCC(ctx context.Context, workspaceID int32) ([]GetOverdueCCRow, error) {
	rows, err := q.db.Query(ctx, getOverdueCC, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueCCRow{}
	for rows.Next() {
		var i GetOverdueCCRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.ID_2,
			&i.WorkspaceID_2,
			&i.Name_2,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCCByMonth = `-- name: GetPendingCCByMonth :many
SELECT t.id, t.workspace_id, account_id, t.name, amount, type, transaction_date, is_paid, notes, t.created_at, t.updated_at, t.deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected, a.id, a.workspace_id, a.name, account_type, template, initial_balance, a.created_at, a.updated_at, a.deleted_at FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND t.billed_at IS NULL
  AND t.is_paid = false
  AND t.transaction_date >= $2 AND t.transaction_date < $3
  AND t.deleted_at IS NULL
ORDER BY t.transaction_date DESC
`

type GetPendingCCByMonthParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetPendingCCByMonthRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	ID_2             int32              `json:"id_2"`
	WorkspaceID_2    int32              `json:"workspace_id_2"`
	Name_2           string             `json:"name_2"`
	AccountType      string             `json:"account_type"`
	Template         string             `json:"template"`
	InitialBalance   pgtype.Numeric     `json:"initial_balance"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2      pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2      pgtype.Timestamptz `json:"deleted_at_2"`
}

// Get pending CC transactions (billed_at IS NULL) for a specific month range
func (q *Queries) GetPendingCCByMonth(ctx context.Context, arg GetPendingCCByMonthParams) ([]GetPendingCCByMonthRow, error) {
	rows, err := q.db.Query(ctx, getPendingCCByMonth, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingCCByMonthRow{}
	for rows.Next() {
		var i GetPendingCCByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.ID_2,
			&i.WorkspaceID_2,
			&i.Name_2,
			&i.AccountType,
			&i.Template,
			&i.InitialBalance,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectionsByTemplate = `-- name: GetProjectionsByTemplate :many

SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected FROM transactions
WHERE workspace_id = $1
  AND template_id = $2
  AND is_projected = true
  AND deleted_at IS NULL
ORDER BY transaction_date
`

type GetProjectionsByTemplateParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	TemplateID  pgtype.Int4 `json:"template_id"`
}

// ========================================
// Projection Management (v2)
// ========================================
// Get all projected transactions for a specific template
func (q *Queries) GetProjectionsByTemplate(ctx context.Context, arg GetProjectionsByTemplateParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getProjectionsByTemplate, arg.WorkspaceID, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyUsedCategories = `-- name: GetRecentlyUsedCategories :many
SELECT DISTINCT
    bc.id,
    bc.name,
    MAX(t.created_at) AS last_used
FROM transactions t
JOIN budget_categories bc ON t.category_id = bc.id AND bc.deleted_at IS NULL
WHERE t.workspace_id = $1
  AND t.deleted_at IS NULL
  AND t.category_id IS NOT NULL
GROUP BY bc.id, bc.name
ORDER BY last_used DESC
LIMIT 5
`

type GetRecentlyUsedCategoriesRow struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	LastUsed interface{} `json:"last_used"`
}

// Returns recently used categories for suggestions dropdown
func (q *Queries) GetRecentlyUsedCategories(ctx context.Context, workspaceID int32) ([]GetRecentlyUsedCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyUsedCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentlyUsedCategoriesRow{}
	for rows.Next() {
		var i GetRecentlyUsedCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LastUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected FROM transactions
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetTransactionByIDParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.WorkspaceID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.BilledAt,
		&i.SettlementIntent,
		&i.Source,
		&i.TemplateID,
		&i.IsProjected,
	)
	return i, err
}

const getTransactionsByIDs = `-- name: GetTransactionsByIDs :many
SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected FROM transactions
WHERE workspace_id = $1
  AND id = ANY($2::int[])
  AND deleted_at IS NULL
ORDER BY id
`

type GetTransactionsByIDsParams struct {
	WorkspaceID int32   `json:"workspace_id"`
	Column2     []int32 `json:"column_2"`
}

// Get multiple transactions by their IDs
func (q *Queries) GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIDs, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByWorkspace = `-- name: GetTransactionsByWorkspace :many
SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR account_id = $2)
  AND ($3::DATE IS NULL OR transaction_date >= $3)
  AND ($4::DATE IS NULL OR transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR type = $5)
ORDER BY transaction_date DESC, created_at DESC
LIMIT $6 OFFSET $7
`

type GetTransactionsByWorkspaceParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	Column2     int32       `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
	Column5     string      `json:"column_5"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) GetTransactionsByWorkspace(ctx context.Context, arg GetTransactionsByWorkspaceParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByWorkspace,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsForAggregation = `-- name: GetTransactionsForAggregation :many
SELECT
    t.id,
    t.workspace_id,
    t.account_id,
    t.name,
    t.amount,
    t.type,
    t.transaction_date,
    t.is_paid,
    t.notes,
    t.transfer_pair_id,
    t.category_id,
    t.is_cc_payment,
    t.created_at,
    t.updated_at,
    t.deleted_at,
    t.billed_at,
    t.settlement_intent,
    t.source,
    t.template_id,
    t.is_projected,
    bc.name AS category_name
FROM transactions t
LEFT JOIN budget_categories bc ON t.category_id = bc.id AND bc.deleted_at IS NULL
WHERE t.workspace_id = $1
  AND t.deleted_at IS NULL
  AND t.transaction_date >= $2::DATE
  AND t.transaction_date <= $3::DATE
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type GetTransactionsForAggregationParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

type GetTransactionsForAggregationRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	CategoryName     pgtype.Text        `json:"category_name"`
}

// Returns all transactions in a date range with category name for aggregation (no pagination)
// Used by dashboard future spending calculations
func (q *Queries) GetTransactionsForAggregation(ctx context.Context, arg GetTransactionsForAggregationParams) ([]GetTransactionsForAggregationRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsForAggregation, arg.WorkspaceID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsForAggregationRow{}
	for rows.Next() {
		var i GetTransactionsForAggregationRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsWithCategory = `-- name: GetTransactionsWithCategory :many
SELECT
    t.id,
    t.workspace_id,
    t.account_id,
    t.name,
    t.amount,
    t.type,
    t.transaction_date,
    t.is_paid,
    t.notes,
    t.transfer_pair_id,
    t.category_id,
    t.is_cc_payment,
    t.created_at,
    t.updated_at,
    t.deleted_at,
    t.billed_at,
    t.settlement_intent,
    t.source,
    t.template_id,
    t.is_projected,
    bc.name AS category_name
FROM transactions t
LEFT JOIN budget_categories bc ON t.category_id = bc.id AND bc.deleted_at IS NULL
WHERE t.workspace_id = $1
  AND t.deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR t.account_id = $2)
  AND ($3::DATE IS NULL OR t.transaction_date >= $3)
  AND ($4::DATE IS NULL OR t.transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR t.type = $5)
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $7 OFFSET $6
`

type GetTransactionsWithCategoryParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	AccountID   pgtype.Int4 `json:"account_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Type        pgtype.Text `json:"type"`
	PageOffset  int32       `json:"page_offset"`
	PageSize    int32       `json:"page_size"`
}

type GetTransactionsWithCategoryRow struct {
	ID               int32              `json:"id"`
	WorkspaceID      int32              `json:"workspace_id"`
	AccountID        int32              `json:"account_id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	IsPaid           bool               `json:"is_paid"`
	Notes            pgtype.Text        `json:"notes"`
	TransferPairID   pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsCcPayment      bool               `json:"is_cc_payment"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
	CategoryName     pgtype.Text        `json:"category_name"`
}

// Returns transactions with category name joined for display
func (q *Queries) GetTransactionsWithCategory(ctx context.Context, arg GetTransactionsWithCategoryParams) ([]GetTransactionsWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsWithCategory,
		arg.WorkspaceID,
		arg.AccountID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsWithCategoryRow{}
	for rows.Next() {
		var i GetTransactionsWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.Notes,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BilledAt,
			&i.SettlementIntent,
			&i.Source,
			&i.TemplateID,
			&i.IsProjected,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanActualsByTemplate = `-- name: OrphanActualsByTemplate :exec
UPDATE transactions
SET template_id = NULL,
    updated_at = NOW()
WHERE workspace_id = $1
  AND template_id = $2
  AND is_projected = false
  AND deleted_at IS NULL
`

type OrphanActualsByTemplateParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	TemplateID  pgtype.Int4 `json:"template_id"`
}

// Unlink actual transactions from template (keep them, clear template_id)
func (q *Queries) OrphanActualsByTemplate(ctx context.Context, arg OrphanActualsByTemplateParams) error {
	_, err := q.db.Exec(ctx, orphanActualsByTemplate, arg.WorkspaceID, arg.TemplateID)
	return err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTransferPair = `-- name: SoftDeleteTransferPair :execrows
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE workspace_id = $1 AND transfer_pair_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransferPairParams struct {
	WorkspaceID    int32       `json:"workspace_id"`
	TransferPairID pgtype.UUID `json:"transfer_pair_id"`
}

func (q *Queries) SoftDeleteTransferPair(ctx context.Context, arg SoftDeleteTransferPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransferPair, arg.WorkspaceID, arg.TransferPairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumDeferredCCByDateRange = `-- name: SumDeferredCCByDateRange :one
SELECT COALESCE(SUM(t.amount), 0)::NUMERIC(12,2) as total
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND t.type = 'expense'
  AND t.is_paid = false
  AND t.settlement_intent = 'deferred'
  AND a.template = 'credit_card'
  AND t.deleted_at IS NULL
`

type SumDeferredCCByDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum deferred CC expenses within a date range
// Used for next month projections
func (q *Queries) SumDeferredCCByDateRange(ctx context.Context, arg SumDeferredCCByDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumDeferredCCByDateRange, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumPaidExpensesByDateRange = `-- name: SumPaidExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = 'expense'
  AND is_paid = true
  AND deleted_at IS NULL
`

type SumPaidExpensesByDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum paid expenses within a date range for in-hand balance calculation
func (q *Queries) SumPaidExpensesByDateRange(ctx context.Context, arg SumPaidExpensesByDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumPaidExpensesByDateRange, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumTransactionsByTypeAndDateRange = `-- name: SumTransactionsByTypeAndDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = $4
  AND is_paid = true
  AND deleted_at IS NULL
`

type SumTransactionsByTypeAndDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	Type              string      `json:"type"`
}

// Only count paid transactions
func (q *Queries) SumTransactionsByTypeAndDateRange(ctx context.Context, arg SumTransactionsByTypeAndDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumTransactionsByTypeAndDateRange,
		arg.WorkspaceID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Type,
	)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumUnpaidExpensesByDateRange = `-- name: SumUnpaidExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = 'expense'
  AND is_paid = false
  AND deleted_at IS NULL
`

type SumUnpaidExpensesByDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum unpaid expenses within a date range (ALL unpaid, including deferred CC)
// Used for balance calculations where all obligations matter
func (q *Queries) SumUnpaidExpensesByDateRange(ctx context.Context, arg SumUnpaidExpensesByDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumUnpaidExpensesByDateRange, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumUnpaidExpensesForDisposable = `-- name: SumUnpaidExpensesForDisposable :one
SELECT COALESCE(SUM(t.amount), 0)::NUMERIC(12,2) as total
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND t.type = 'expense'
  AND t.is_paid = false
  AND t.deleted_at IS NULL
  AND NOT (a.template = 'credit_card' AND t.settlement_intent = 'deferred')
`

type SumUnpaidExpensesForDisposableParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum unpaid expenses for disposable income calculation
// EXCLUDES deferred CC transactions (those are for next month)
// Includes: non-CC unpaid expenses + immediate CC expenses
func (q *Queries) SumUnpaidExpensesForDisposable(ctx context.Context, arg SumUnpaidExpensesForDisposableParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumUnpaidExpensesForDisposable, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const toggleBilledStatus = `-- name: ToggleBilledStatus :one

UPDATE transactions
SET billed_at = CASE WHEN billed_at IS NULL THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type ToggleBilledStatusParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

// ========================================
// CC Lifecycle Operations (v2 - Simplified)
// CC State: pending (billed_at IS NULL), billed (billed_at IS NOT NULL, is_paid=false), settled (is_paid=true)
// ========================================
// Toggle billed status for a CC transaction (pending <-> billed)
func (q *Queries) ToggleBilledStatus(ctx context.Context, arg ToggleBilledStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, toggleBilledStatus, arg.ID, arg.WorkspaceID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.BilledAt,
		&i.SettlementIntent,
		&i.Source,
		&i.TemplateID,
		&i.IsProjected,
	)
	return i, err
}

const toggleTransactionPaidStatus = `-- name: ToggleTransactionPaidStatus :one
UPDATE transactions
SET is_paid = NOT is_paid, updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type ToggleTransactionPaidStatusParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) ToggleTransactionPaidStatus(ctx context.Context, arg ToggleTransactionPaidStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, toggleTransactionPaidStatus, arg.WorkspaceID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.BilledAt,
		&i.SettlementIntent,
		&i.Source,
		&i.TemplateID,
		&i.IsProjected,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    name = $3,
    amount = $4,
    type = $5,
    transaction_date = $6,
    account_id = $7,
    notes = $8,
    category_id = $9,
    is_paid = $10,
    billed_at = $11,
    settlement_intent = $12,
    source = $13,
    template_id = $14,
    is_projected = $15,
    updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, billed_at, settlement_intent, source, template_id, is_projected
`

type UpdateTransactionParams struct {
	WorkspaceID      int32              `json:"workspace_id"`
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Amount           pgtype.Numeric     `json:"amount"`
	Type             string             `json:"type"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	AccountID        int32              `json:"account_id"`
	Notes            pgtype.Text        `json:"notes"`
	CategoryID       pgtype.Int4        `json:"category_id"`
	IsPaid           bool               `json:"is_paid"`
	BilledAt         pgtype.Timestamptz `json:"billed_at"`
	SettlementIntent pgtype.Text        `json:"settlement_intent"`
	Source           pgtype.Text        `json:"source"`
	TemplateID       pgtype.Int4        `json:"template_id"`
	IsProjected      pgtype.Bool        `json:"is_projected"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.AccountID,
		arg.Notes,
		arg.CategoryID,
		arg.IsPaid,
		arg.BilledAt,
		arg.SettlementIntent,
		arg.Source,
		arg.TemplateID,
		arg.IsProjected,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.BilledAt,
		&i.SettlementIntent,
		&i.Source,
		&i.TemplateID,
		&i.IsProjected,
	)
	return i, err
}
