// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByWorkspace = `-- name: CountTransactionsByWorkspace :one
SELECT COUNT(*) FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR account_id = $2)
  AND ($3::DATE IS NULL OR transaction_date >= $3)
  AND ($4::DATE IS NULL OR transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR type = $5)
`

type CountTransactionsByWorkspaceParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	Column2     int32       `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
	Column5     string      `json:"column_5"`
}

func (q *Queries) CountTransactionsByWorkspace(ctx context.Context, arg CountTransactionsByWorkspaceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByWorkspace,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    workspace_id, account_id, name, amount, type,
    transaction_date, is_paid, cc_settlement_intent, notes, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id
`

type CreateTransactionParams struct {
	WorkspaceID            int32          `json:"workspace_id"`
	AccountID              int32          `json:"account_id"`
	Name                   string         `json:"name"`
	Amount                 pgtype.Numeric `json:"amount"`
	Type                   string         `json:"type"`
	TransactionDate        pgtype.Date    `json:"transaction_date"`
	IsPaid                 bool           `json:"is_paid"`
	CcSettlementIntent     pgtype.Text    `json:"cc_settlement_intent"`
	Notes                  pgtype.Text    `json:"notes"`
	TransferPairID         pgtype.UUID    `json:"transfer_pair_id"`
	CategoryID             pgtype.Int4    `json:"category_id"`
	IsCcPayment            bool           `json:"is_cc_payment"`
	RecurringTransactionID pgtype.Int4    `json:"recurring_transaction_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.IsPaid,
		arg.CcSettlementIntent,
		arg.Notes,
		arg.TransferPairID,
		arg.CategoryID,
		arg.IsCcPayment,
		arg.RecurringTransactionID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.CcSettlementIntent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.RecurringTransactionID,
	)
	return i, err
}

const getAccountTransactionSummaries = `-- name: GetAccountTransactionSummaries :many
SELECT
    account_id,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0) AS sum_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0) AS sum_expenses,
    COALESCE(SUM(CASE WHEN type = 'expense' AND is_paid = false THEN amount ELSE 0 END), 0) AS sum_unpaid_expenses
FROM transactions
WHERE workspace_id = $1 AND deleted_at IS NULL
GROUP BY account_id
`

type GetAccountTransactionSummariesRow struct {
	AccountID         int32       `json:"account_id"`
	SumIncome         interface{} `json:"sum_income"`
	SumExpenses       interface{} `json:"sum_expenses"`
	SumUnpaidExpenses interface{} `json:"sum_unpaid_expenses"`
}

func (q *Queries) GetAccountTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetAccountTransactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, getAccountTransactionSummaries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountTransactionSummariesRow{}
	for rows.Next() {
		var i GetAccountTransactionSummariesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.SumIncome,
			&i.SumExpenses,
			&i.SumUnpaidExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCCPayableBreakdown = `-- name: GetCCPayableBreakdown :many
SELECT
    t.id,
    t.name,
    t.amount,
    t.transaction_date,
    t.cc_settlement_intent,
    t.account_id,
    a.name as account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
    AND a.template = 'credit_card'
    AND t.type = 'expense'
    AND t.is_paid = false
    AND t.deleted_at IS NULL
    AND a.deleted_at IS NULL
ORDER BY t.cc_settlement_intent, a.name, t.transaction_date DESC
`

type GetCCPayableBreakdownRow struct {
	ID                 int32          `json:"id"`
	Name               string         `json:"name"`
	Amount             pgtype.Numeric `json:"amount"`
	TransactionDate    pgtype.Date    `json:"transaction_date"`
	CcSettlementIntent pgtype.Text    `json:"cc_settlement_intent"`
	AccountID          int32          `json:"account_id"`
	AccountName        string         `json:"account_name"`
}

// Get all unpaid CC transactions with settlement intent for payable breakdown
func (q *Queries) GetCCPayableBreakdown(ctx context.Context, workspaceID int32) ([]GetCCPayableBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCCPayableBreakdown, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCCPayableBreakdownRow{}
	for rows.Next() {
		var i GetCCPayableBreakdownRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.TransactionDate,
			&i.CcSettlementIntent,
			&i.AccountID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCCPayableSummary = `-- name: GetCCPayableSummary :many
SELECT
    cc_settlement_intent,
    COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE t.workspace_id = $1
  AND a.template = 'credit_card'
  AND a.deleted_at IS NULL
  AND t.type = 'expense'
  AND t.is_paid = false
  AND t.deleted_at IS NULL
  AND t.cc_settlement_intent IS NOT NULL
GROUP BY cc_settlement_intent
`

type GetCCPayableSummaryRow struct {
	CcSettlementIntent pgtype.Text    `json:"cc_settlement_intent"`
	Total              pgtype.Numeric `json:"total"`
}

// Get unpaid CC transaction totals grouped by settlement intent
func (q *Queries) GetCCPayableSummary(ctx context.Context, workspaceID int32) ([]GetCCPayableSummaryRow, error) {
	rows, err := q.db.Query(ctx, getCCPayableSummary, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCCPayableSummaryRow{}
	for rows.Next() {
		var i GetCCPayableSummaryRow
		if err := rows.Scan(&i.CcSettlementIntent, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTransactionSummaries = `-- name: GetMonthlyTransactionSummaries :many
SELECT
    EXTRACT(YEAR FROM transaction_date)::INTEGER AS year,
    EXTRACT(MONTH FROM transaction_date)::INTEGER AS month,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS total_expenses
FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
GROUP BY EXTRACT(YEAR FROM transaction_date), EXTRACT(MONTH FROM transaction_date)
ORDER BY year DESC, month DESC
`

type GetMonthlyTransactionSummariesRow struct {
	Year          int32          `json:"year"`
	Month         int32          `json:"month"`
	TotalIncome   pgtype.Numeric `json:"total_income"`
	TotalExpenses pgtype.Numeric `json:"total_expenses"`
}

// Batch query to get income/expense totals grouped by year/month for N+1 prevention
func (q *Queries) GetMonthlyTransactionSummaries(ctx context.Context, workspaceID int32) ([]GetMonthlyTransactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTransactionSummaries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTransactionSummariesRow{}
	for rows.Next() {
		var i GetMonthlyTransactionSummariesRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.TotalIncome,
			&i.TotalExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyUsedCategories = `-- name: GetRecentlyUsedCategories :many
SELECT DISTINCT
    bc.id,
    bc.name,
    MAX(t.created_at) AS last_used
FROM transactions t
JOIN budget_categories bc ON t.category_id = bc.id AND bc.deleted_at IS NULL
WHERE t.workspace_id = $1
  AND t.deleted_at IS NULL
  AND t.category_id IS NOT NULL
GROUP BY bc.id, bc.name
ORDER BY last_used DESC
LIMIT 5
`

type GetRecentlyUsedCategoriesRow struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	LastUsed interface{} `json:"last_used"`
}

// Returns recently used categories for suggestions dropdown
func (q *Queries) GetRecentlyUsedCategories(ctx context.Context, workspaceID int32) ([]GetRecentlyUsedCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyUsedCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentlyUsedCategoriesRow{}
	for rows.Next() {
		var i GetRecentlyUsedCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LastUsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id FROM transactions
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetTransactionByIDParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.WorkspaceID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.CcSettlementIntent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.RecurringTransactionID,
	)
	return i, err
}

const getTransactionsByWorkspace = `-- name: GetTransactionsByWorkspace :many
SELECT id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id FROM transactions
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR account_id = $2)
  AND ($3::DATE IS NULL OR transaction_date >= $3)
  AND ($4::DATE IS NULL OR transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR type = $5)
ORDER BY transaction_date DESC, created_at DESC
LIMIT $6 OFFSET $7
`

type GetTransactionsByWorkspaceParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	Column2     int32       `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
	Column5     string      `json:"column_5"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) GetTransactionsByWorkspace(ctx context.Context, arg GetTransactionsByWorkspaceParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByWorkspace,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.CcSettlementIntent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.RecurringTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsWithCategory = `-- name: GetTransactionsWithCategory :many
SELECT
    t.id,
    t.workspace_id,
    t.account_id,
    t.name,
    t.amount,
    t.type,
    t.transaction_date,
    t.is_paid,
    t.cc_settlement_intent,
    t.notes,
    t.transfer_pair_id,
    t.category_id,
    t.is_cc_payment,
    t.recurring_transaction_id,
    t.created_at,
    t.updated_at,
    t.deleted_at,
    bc.name AS category_name
FROM transactions t
LEFT JOIN budget_categories bc ON t.category_id = bc.id AND bc.deleted_at IS NULL
WHERE t.workspace_id = $1
  AND t.deleted_at IS NULL
  AND ($2::INTEGER IS NULL OR t.account_id = $2)
  AND ($3::DATE IS NULL OR t.transaction_date >= $3)
  AND ($4::DATE IS NULL OR t.transaction_date <= $4)
  AND ($5::VARCHAR IS NULL OR t.type = $5)
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $6 OFFSET $7
`

type GetTransactionsWithCategoryParams struct {
	WorkspaceID int32       `json:"workspace_id"`
	Column2     int32       `json:"column_2"`
	Column3     pgtype.Date `json:"column_3"`
	Column4     pgtype.Date `json:"column_4"`
	Column5     string      `json:"column_5"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type GetTransactionsWithCategoryRow struct {
	ID                     int32              `json:"id"`
	WorkspaceID            int32              `json:"workspace_id"`
	AccountID              int32              `json:"account_id"`
	Name                   string             `json:"name"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Type                   string             `json:"type"`
	TransactionDate        pgtype.Date        `json:"transaction_date"`
	IsPaid                 bool               `json:"is_paid"`
	CcSettlementIntent     pgtype.Text        `json:"cc_settlement_intent"`
	Notes                  pgtype.Text        `json:"notes"`
	TransferPairID         pgtype.UUID        `json:"transfer_pair_id"`
	CategoryID             pgtype.Int4        `json:"category_id"`
	IsCcPayment            bool               `json:"is_cc_payment"`
	RecurringTransactionID pgtype.Int4        `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CategoryName           pgtype.Text        `json:"category_name"`
}

// Returns transactions with category name joined for display
func (q *Queries) GetTransactionsWithCategory(ctx context.Context, arg GetTransactionsWithCategoryParams) ([]GetTransactionsWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsWithCategory,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsWithCategoryRow{}
	for rows.Next() {
		var i GetTransactionsWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Amount,
			&i.Type,
			&i.TransactionDate,
			&i.IsPaid,
			&i.CcSettlementIntent,
			&i.Notes,
			&i.TransferPairID,
			&i.CategoryID,
			&i.IsCcPayment,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTransferPair = `-- name: SoftDeleteTransferPair :execrows
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE workspace_id = $1 AND transfer_pair_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransferPairParams struct {
	WorkspaceID    int32       `json:"workspace_id"`
	TransferPairID pgtype.UUID `json:"transfer_pair_id"`
}

func (q *Queries) SoftDeleteTransferPair(ctx context.Context, arg SoftDeleteTransferPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransferPair, arg.WorkspaceID, arg.TransferPairID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumPaidExpensesByDateRange = `-- name: SumPaidExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = 'expense'
  AND is_paid = true
  AND deleted_at IS NULL
`

type SumPaidExpensesByDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum paid expenses within a date range for in-hand balance calculation
func (q *Queries) SumPaidExpensesByDateRange(ctx context.Context, arg SumPaidExpensesByDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumPaidExpensesByDateRange, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumTransactionsByTypeAndDateRange = `-- name: SumTransactionsByTypeAndDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = $4
  AND deleted_at IS NULL
`

type SumTransactionsByTypeAndDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	Type              string      `json:"type"`
}

func (q *Queries) SumTransactionsByTypeAndDateRange(ctx context.Context, arg SumTransactionsByTypeAndDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumTransactionsByTypeAndDateRange,
		arg.WorkspaceID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Type,
	)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumUnpaidExpensesByDateRange = `-- name: SumUnpaidExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) as total
FROM transactions
WHERE workspace_id = $1
  AND transaction_date >= $2
  AND transaction_date <= $3
  AND type = 'expense'
  AND is_paid = false
  AND deleted_at IS NULL
`

type SumUnpaidExpensesByDateRangeParams struct {
	WorkspaceID       int32       `json:"workspace_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

// Sum unpaid expenses within a date range for disposable income calculation
func (q *Queries) SumUnpaidExpensesByDateRange(ctx context.Context, arg SumUnpaidExpensesByDateRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumUnpaidExpensesByDateRange, arg.WorkspaceID, arg.TransactionDate, arg.TransactionDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const toggleTransactionPaidStatus = `-- name: ToggleTransactionPaidStatus :one
UPDATE transactions
SET is_paid = NOT is_paid, updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id
`

type ToggleTransactionPaidStatusParams struct {
	WorkspaceID int32 `json:"workspace_id"`
	ID          int32 `json:"id"`
}

func (q *Queries) ToggleTransactionPaidStatus(ctx context.Context, arg ToggleTransactionPaidStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, toggleTransactionPaidStatus, arg.WorkspaceID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.CcSettlementIntent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.RecurringTransactionID,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    name = $3,
    amount = $4,
    type = $5,
    transaction_date = $6,
    account_id = $7,
    cc_settlement_intent = $8,
    notes = $9,
    category_id = $10,
    updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id
`

type UpdateTransactionParams struct {
	WorkspaceID        int32          `json:"workspace_id"`
	ID                 int32          `json:"id"`
	Name               string         `json:"name"`
	Amount             pgtype.Numeric `json:"amount"`
	Type               string         `json:"type"`
	TransactionDate    pgtype.Date    `json:"transaction_date"`
	AccountID          int32          `json:"account_id"`
	CcSettlementIntent pgtype.Text    `json:"cc_settlement_intent"`
	Notes              pgtype.Text    `json:"notes"`
	CategoryID         pgtype.Int4    `json:"category_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Type,
		arg.TransactionDate,
		arg.AccountID,
		arg.CcSettlementIntent,
		arg.Notes,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.CcSettlementIntent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.RecurringTransactionID,
	)
	return i, err
}

const updateTransactionSettlementIntent = `-- name: UpdateTransactionSettlementIntent :one
UPDATE transactions
SET cc_settlement_intent = $3, updated_at = NOW()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL AND is_paid = false
RETURNING id, workspace_id, account_id, name, amount, type, transaction_date, is_paid, cc_settlement_intent, notes, created_at, updated_at, deleted_at, transfer_pair_id, category_id, is_cc_payment, recurring_transaction_id
`

type UpdateTransactionSettlementIntentParams struct {
	WorkspaceID        int32       `json:"workspace_id"`
	ID                 int32       `json:"id"`
	CcSettlementIntent pgtype.Text `json:"cc_settlement_intent"`
}

func (q *Queries) UpdateTransactionSettlementIntent(ctx context.Context, arg UpdateTransactionSettlementIntentParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionSettlementIntent, arg.WorkspaceID, arg.ID, arg.CcSettlementIntent)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Amount,
		&i.Type,
		&i.TransactionDate,
		&i.IsPaid,
		&i.CcSettlementIntent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TransferPairID,
		&i.CategoryID,
		&i.IsCcPayment,
		&i.RecurringTransactionID,
	)
	return i, err
}
