// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrGetUserByAuth0ID = `-- name: CreateOrGetUserByAuth0ID :one
INSERT INTO users (auth0_id, email, name, picture_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth0_id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    picture_url = EXCLUDED.picture_url,
    updated_at = NOW()
RETURNING id, auth0_id, email, name, picture_url, created_at, updated_at
`

type CreateOrGetUserByAuth0IDParams struct {
	Auth0ID    string      `json:"auth0_id"`
	Email      string      `json:"email"`
	Name       pgtype.Text `json:"name"`
	PictureUrl pgtype.Text `json:"picture_url"`
}

func (q *Queries) CreateOrGetUserByAuth0ID(ctx context.Context, arg CreateOrGetUserByAuth0IDParams) (User, error) {
	row := q.db.QueryRow(ctx, createOrGetUserByAuth0ID,
		arg.Auth0ID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth0_id, email, name, picture_url)
VALUES ($1, $2, $3, $4)
RETURNING id, auth0_id, email, name, picture_url, created_at, updated_at
`

type CreateUserParams struct {
	Auth0ID    string      `json:"auth0_id"`
	Email      string      `json:"email"`
	Name       pgtype.Text `json:"name"`
	PictureUrl pgtype.Text `json:"picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Auth0ID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuth0ID = `-- name: GetUserByAuth0ID :one
SELECT id, auth0_id, email, name, picture_url, created_at, updated_at FROM users WHERE auth0_id = $1
`

func (q *Queries) GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0ID, auth0ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth0_id, email, name, picture_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, name = $3, picture_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, auth0_id, email, name, picture_url, created_at, updated_at
`

type UpdateUserParams struct {
	ID         pgtype.UUID `json:"id"`
	Email      string      `json:"email"`
	Name       pgtype.Text `json:"name"`
	PictureUrl pgtype.Text `json:"picture_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $2, updated_at = NOW()
WHERE auth0_id = $1
RETURNING id, auth0_id, email, name, picture_url, created_at, updated_at
`

type UpdateUserNameParams struct {
	Auth0ID string      `json:"auth0_id"`
	Name    pgtype.Text `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Auth0ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
