// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlist_item_prices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWishlistItemPrice = `-- name: CreateWishlistItemPrice :one
INSERT INTO wishlist_item_prices (item_id, platform_name, price, price_date, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_id, platform_name, price, price_date, image_url, created_at
`

type CreateWishlistItemPriceParams struct {
	ItemID       int32          `json:"item_id"`
	PlatformName string         `json:"platform_name"`
	Price        pgtype.Numeric `json:"price"`
	PriceDate    pgtype.Date    `json:"price_date"`
	ImageUrl     pgtype.Text    `json:"image_url"`
}

func (q *Queries) CreateWishlistItemPrice(ctx context.Context, arg CreateWishlistItemPriceParams) (WishlistItemPrice, error) {
	row := q.db.QueryRow(ctx, createWishlistItemPrice,
		arg.ItemID,
		arg.PlatformName,
		arg.Price,
		arg.PriceDate,
		arg.ImageUrl,
	)
	var i WishlistItemPrice
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlatformName,
		&i.Price,
		&i.PriceDate,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWishlistItemPrice = `-- name: DeleteWishlistItemPrice :exec
DELETE FROM wishlist_item_prices wip
USING wishlist_items wi, wishlists w
WHERE wip.id = $1 AND wip.item_id = wi.id AND wi.wishlist_id = w.id AND w.workspace_id = $2
AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
`

type DeleteWishlistItemPriceParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) DeleteWishlistItemPrice(ctx context.Context, arg DeleteWishlistItemPriceParams) error {
	_, err := q.db.Exec(ctx, deleteWishlistItemPrice, arg.ID, arg.WorkspaceID)
	return err
}

const getBestPriceForItem = `-- name: GetBestPriceForItem :one
SELECT MIN(current_prices.price)::TEXT as best_price
FROM (
    SELECT DISTINCT ON (wip.platform_name) wip.price
    FROM wishlist_item_prices wip
    JOIN wishlist_items wi ON wi.id = wip.item_id
    JOIN wishlists w ON w.id = wi.wishlist_id
    WHERE wip.item_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
    ORDER BY wip.platform_name, wip.price_date DESC, wip.created_at DESC
) AS current_prices
`

type GetBestPriceForItemParams struct {
	ItemID      int32 `json:"item_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetBestPriceForItem(ctx context.Context, arg GetBestPriceForItemParams) (string, error) {
	row := q.db.QueryRow(ctx, getBestPriceForItem, arg.ItemID, arg.WorkspaceID)
	var best_price string
	err := row.Scan(&best_price)
	return best_price, err
}

const getCurrentPricesByItem = `-- name: GetCurrentPricesByItem :many
SELECT DISTINCT ON (wip.platform_name)
    wip.id, wip.item_id, wip.platform_name, wip.price, wip.price_date, wip.image_url, wip.created_at
FROM wishlist_item_prices wip
JOIN wishlist_items wi ON wi.id = wip.item_id
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wip.item_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wip.platform_name, wip.price_date DESC, wip.created_at DESC
`

type GetCurrentPricesByItemParams struct {
	ItemID      int32 `json:"item_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetCurrentPricesByItem(ctx context.Context, arg GetCurrentPricesByItemParams) ([]WishlistItemPrice, error) {
	rows, err := q.db.Query(ctx, getCurrentPricesByItem, arg.ItemID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishlistItemPrice{}
	for rows.Next() {
		var i WishlistItemPrice
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PlatformName,
			&i.Price,
			&i.PriceDate,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceHistoryByPlatform = `-- name: GetPriceHistoryByPlatform :many
SELECT wip.id, wip.item_id, wip.platform_name, wip.price, wip.price_date, wip.image_url, wip.created_at FROM wishlist_item_prices wip
JOIN wishlist_items wi ON wi.id = wip.item_id
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wip.item_id = $1 AND wip.platform_name = $2 AND w.workspace_id = $3
AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wip.price_date DESC, wip.created_at DESC
`

type GetPriceHistoryByPlatformParams struct {
	ItemID       int32  `json:"item_id"`
	PlatformName string `json:"platform_name"`
	WorkspaceID  int32  `json:"workspace_id"`
}

func (q *Queries) GetPriceHistoryByPlatform(ctx context.Context, arg GetPriceHistoryByPlatformParams) ([]WishlistItemPrice, error) {
	rows, err := q.db.Query(ctx, getPriceHistoryByPlatform, arg.ItemID, arg.PlatformName, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishlistItemPrice{}
	for rows.Next() {
		var i WishlistItemPrice
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PlatformName,
			&i.Price,
			&i.PriceDate,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWishlistItemPriceByID = `-- name: GetWishlistItemPriceByID :one
SELECT wip.id, wip.item_id, wip.platform_name, wip.price, wip.price_date, wip.image_url, wip.created_at FROM wishlist_item_prices wip
JOIN wishlist_items wi ON wi.id = wip.item_id
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wip.id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
`

type GetWishlistItemPriceByIDParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetWishlistItemPriceByID(ctx context.Context, arg GetWishlistItemPriceByIDParams) (WishlistItemPrice, error) {
	row := q.db.QueryRow(ctx, getWishlistItemPriceByID, arg.ID, arg.WorkspaceID)
	var i WishlistItemPrice
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PlatformName,
		&i.Price,
		&i.PriceDate,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listPricesByItem = `-- name: ListPricesByItem :many
SELECT wip.id, wip.item_id, wip.platform_name, wip.price, wip.price_date, wip.image_url, wip.created_at FROM wishlist_item_prices wip
JOIN wishlist_items wi ON wi.id = wip.item_id
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wip.item_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wip.platform_name, wip.price_date DESC, wip.created_at DESC
`

type ListPricesByItemParams struct {
	ItemID      int32 `json:"item_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) ListPricesByItem(ctx context.Context, arg ListPricesByItemParams) ([]WishlistItemPrice, error) {
	rows, err := q.db.Query(ctx, listPricesByItem, arg.ItemID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishlistItemPrice{}
	for rows.Next() {
		var i WishlistItemPrice
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PlatformName,
			&i.Price,
			&i.PriceDate,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
