// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlist_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWishlistItems = `-- name: CountWishlistItems :one
SELECT COUNT(*) FROM wishlist_items wi
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wi.wishlist_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
`

type CountWishlistItemsParams struct {
	WishlistID  int32 `json:"wishlist_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) CountWishlistItems(ctx context.Context, arg CountWishlistItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWishlistItems, arg.WishlistID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWishlistItem = `-- name: CreateWishlistItem :one
INSERT INTO wishlist_items (wishlist_id, title, description, external_link, image_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, wishlist_id, title, description, external_link, image_url, created_at, updated_at, deleted_at, image_path
`

type CreateWishlistItemParams struct {
	WishlistID   int32       `json:"wishlist_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	ExternalLink pgtype.Text `json:"external_link"`
	ImagePath    pgtype.Text `json:"image_path"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, createWishlistItem,
		arg.WishlistID,
		arg.Title,
		arg.Description,
		arg.ExternalLink,
		arg.ImagePath,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.ExternalLink,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ImagePath,
	)
	return i, err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
UPDATE wishlist_items wi
SET deleted_at = NOW()
FROM wishlists w
WHERE wi.id = $1 AND w.id = wi.wishlist_id AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
`

type DeleteWishlistItemParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error {
	_, err := q.db.Exec(ctx, deleteWishlistItem, arg.ID, arg.WorkspaceID)
	return err
}

const getFirstItemImage = `-- name: GetFirstItemImage :one
SELECT wi.image_path FROM wishlist_items wi
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wi.wishlist_id = $1 AND w.workspace_id = $2 AND wi.image_path IS NOT NULL AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wi.created_at ASC
LIMIT 1
`

type GetFirstItemImageParams struct {
	WishlistID  int32 `json:"wishlist_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetFirstItemImage(ctx context.Context, arg GetFirstItemImageParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getFirstItemImage, arg.WishlistID, arg.WorkspaceID)
	var image_path pgtype.Text
	err := row.Scan(&image_path)
	return image_path, err
}

const getWishlistItemByID = `-- name: GetWishlistItemByID :one
SELECT wi.id, wi.wishlist_id, wi.title, wi.description, wi.external_link, wi.image_url, wi.created_at, wi.updated_at, wi.deleted_at, wi.image_path FROM wishlist_items wi
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wi.id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
`

type GetWishlistItemByIDParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetWishlistItemByID(ctx context.Context, arg GetWishlistItemByIDParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, getWishlistItemByID, arg.ID, arg.WorkspaceID)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.ExternalLink,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ImagePath,
	)
	return i, err
}

const listWishlistItems = `-- name: ListWishlistItems :many
SELECT wi.id, wi.wishlist_id, wi.title, wi.description, wi.external_link, wi.image_url, wi.created_at, wi.updated_at, wi.deleted_at, wi.image_path FROM wishlist_items wi
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wi.wishlist_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wi.created_at DESC
`

type ListWishlistItemsParams struct {
	WishlistID  int32 `json:"wishlist_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) ListWishlistItems(ctx context.Context, arg ListWishlistItemsParams) ([]WishlistItem, error) {
	rows, err := q.db.Query(ctx, listWishlistItems, arg.WishlistID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishlistItem{}
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.WishlistID,
			&i.Title,
			&i.Description,
			&i.ExternalLink,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistItemsWithStats = `-- name: ListWishlistItemsWithStats :many
SELECT
    wi.id, wi.wishlist_id, wi.title, wi.description, wi.external_link, wi.image_url, wi.created_at, wi.updated_at, wi.deleted_at, wi.image_path,
    (
        SELECT MIN(current_prices.price)::TEXT
        FROM (
            SELECT DISTINCT ON (wip.platform_name) wip.price
            FROM wishlist_item_prices wip
            WHERE wip.item_id = wi.id
            ORDER BY wip.platform_name, wip.price_date DESC, wip.created_at DESC
        ) AS current_prices
    ) AS best_price,
    0::int AS note_count  -- Placeholder for Story 8-5
FROM wishlist_items wi
JOIN wishlists w ON w.id = wi.wishlist_id
WHERE wi.wishlist_id = $1 AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
ORDER BY wi.created_at DESC
`

type ListWishlistItemsWithStatsParams struct {
	WishlistID  int32 `json:"wishlist_id"`
	WorkspaceID int32 `json:"workspace_id"`
}

type ListWishlistItemsWithStatsRow struct {
	ID           int32              `json:"id"`
	WishlistID   int32              `json:"wishlist_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	ExternalLink pgtype.Text        `json:"external_link"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ImagePath    pgtype.Text        `json:"image_path"`
	BestPrice    string             `json:"best_price"`
	NoteCount    int32              `json:"note_count"`
}

func (q *Queries) ListWishlistItemsWithStats(ctx context.Context, arg ListWishlistItemsWithStatsParams) ([]ListWishlistItemsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listWishlistItemsWithStats, arg.WishlistID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWishlistItemsWithStatsRow{}
	for rows.Next() {
		var i ListWishlistItemsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.WishlistID,
			&i.Title,
			&i.Description,
			&i.ExternalLink,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ImagePath,
			&i.BestPrice,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveWishlistItem = `-- name: MoveWishlistItem :one
UPDATE wishlist_items wi
SET wishlist_id = $3, updated_at = NOW()
FROM wishlists w
WHERE wi.id = $1 AND w.id = wi.wishlist_id AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
RETURNING wi.id, wi.wishlist_id, wi.title, wi.description, wi.external_link, wi.image_url, wi.created_at, wi.updated_at, wi.deleted_at, wi.image_path
`

type MoveWishlistItemParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
	WishlistID  int32 `json:"wishlist_id"`
}

func (q *Queries) MoveWishlistItem(ctx context.Context, arg MoveWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, moveWishlistItem, arg.ID, arg.WorkspaceID, arg.WishlistID)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.ExternalLink,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ImagePath,
	)
	return i, err
}

const updateWishlistItem = `-- name: UpdateWishlistItem :one
UPDATE wishlist_items wi
SET title = $3, description = $4, external_link = $5, image_path = $6, updated_at = NOW()
FROM wishlists w
WHERE wi.id = $1 AND w.id = wi.wishlist_id AND w.workspace_id = $2 AND wi.deleted_at IS NULL AND w.deleted_at IS NULL
RETURNING wi.id, wi.wishlist_id, wi.title, wi.description, wi.external_link, wi.image_url, wi.created_at, wi.updated_at, wi.deleted_at, wi.image_path
`

type UpdateWishlistItemParams struct {
	ID           int32       `json:"id"`
	WorkspaceID  int32       `json:"workspace_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	ExternalLink pgtype.Text `json:"external_link"`
	ImagePath    pgtype.Text `json:"image_path"`
}

func (q *Queries) UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, updateWishlistItem,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
		arg.ExternalLink,
		arg.ImagePath,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.ExternalLink,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ImagePath,
	)
	return i, err
}
