// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlists.sql

package sqlc

import (
	"context"
)

const createWishlist = `-- name: CreateWishlist :one
INSERT INTO wishlists (workspace_id, name)
VALUES ($1, $2)
RETURNING id, workspace_id, name, created_at, updated_at, deleted_at
`

type CreateWishlistParams struct {
	WorkspaceID int32  `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateWishlist(ctx context.Context, arg CreateWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, createWishlist, arg.WorkspaceID, arg.Name)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWishlist = `-- name: DeleteWishlist :exec
UPDATE wishlists
SET deleted_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type DeleteWishlistParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) DeleteWishlist(ctx context.Context, arg DeleteWishlistParams) error {
	_, err := q.db.Exec(ctx, deleteWishlist, arg.ID, arg.WorkspaceID)
	return err
}

const getWishlistByID = `-- name: GetWishlistByID :one
SELECT id, workspace_id, name, created_at, updated_at, deleted_at FROM wishlists
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetWishlistByIDParams struct {
	ID          int32 `json:"id"`
	WorkspaceID int32 `json:"workspace_id"`
}

func (q *Queries) GetWishlistByID(ctx context.Context, arg GetWishlistByIDParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, getWishlistByID, arg.ID, arg.WorkspaceID)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWishlistByName = `-- name: GetWishlistByName :one
SELECT id, workspace_id, name, created_at, updated_at, deleted_at FROM wishlists
WHERE workspace_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetWishlistByNameParams struct {
	WorkspaceID int32  `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetWishlistByName(ctx context.Context, arg GetWishlistByNameParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, getWishlistByName, arg.WorkspaceID, arg.Name)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWishlists = `-- name: ListWishlists :many
SELECT id, workspace_id, name, created_at, updated_at, deleted_at FROM wishlists
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWishlists(ctx context.Context, workspaceID int32) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, listWishlists, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wishlist{}
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWishlist = `-- name: UpdateWishlist :one
UPDATE wishlists
SET name = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, name, created_at, updated_at, deleted_at
`

type UpdateWishlistParams struct {
	ID          int32  `json:"id"`
	WorkspaceID int32  `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpdateWishlist(ctx context.Context, arg UpdateWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, updateWishlist, arg.ID, arg.WorkspaceID, arg.Name)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
