// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWorkspaceData = `-- name: ClearWorkspaceData :exec
DELETE FROM wishlist_items WHERE wishlist_id IN (SELECT id FROM wishlists WHERE workspace_id = $1)
`

// Delete all data for a workspace (but keep the workspace itself)
// Order matters due to foreign key constraints
// Note: Some deletes will cascade automatically (e.g., wishlist_item_notes, wishlist_item_prices, loan_payments)
// but we're explicit here for clarity and to handle all cases
func (q *Queries) ClearWorkspaceData(ctx context.Context, workspaceID int32) error {
	_, err := q.db.Exec(ctx, clearWorkspaceData, workspaceID)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateWorkspaceParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.UserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getAllWorkspaces = `-- name: GetAllWorkspaces :many
SELECT id, user_id, name, created_at, updated_at FROM workspaces ORDER BY id
`

// Used by projection worker to sync all workspaces
func (q *Queries) GetAllWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getAllWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, user_id, name, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int32) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByUserAuth0ID = `-- name: GetWorkspaceByUserAuth0ID :one
SELECT w.id, w.user_id, w.name, w.created_at, w.updated_at FROM workspaces w
INNER JOIN users u ON w.user_id = u.id
WHERE u.auth0_id = $1
`

func (q *Queries) GetWorkspaceByUserAuth0ID(ctx context.Context, auth0ID string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByUserAuth0ID, auth0ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByUserID = `-- name: GetWorkspaceByUserID :one
SELECT id, user_id, name, created_at, updated_at FROM workspaces WHERE user_id = $1
`

func (q *Queries) GetWorkspaceByUserID(ctx context.Context, userID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByUserID, userID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
